SOURCES = 	 tabs/__init__.py\
			 tabs/Archeozoology.py\
			 tabs/Campioni.py\
			 tabs/Deteta.py\
			 tabs/Detsesso.py\
			 tabs/Documentazione.py\
			 tabs/Documentazione_preview.py\
			 tabs/Gis_Time_controller.py\
			 tabs/Image_viewer.py\
			 tabs/Images_comparison.py\
			 tabs/Images_directory_export.py\
			 tabs/Interactive_matrix.py\
			 tabs/Inv_Lapidei.py\
			 tabs/Inv_Materiali.py\
			 tabs/Pdf_administrator.py\
			 tabs/Pdf_export.py\
			 tabs/Periodizzazione.py\
			 tabs/Schedaind.py\
			 tabs/Site.py\
			 tabs/Struttura.py\
			 tabs/Tafonomia.py\
			 tabs/Thesaurus.py\
			 tabs/Upd.py\
			 tabs/US_USM.py\
			 tabs/UT.py\
			 gui/__init__.py\
			 gui/dbmanagment.py\
			 gui/imageViewer.py\
			 gui/pyarchinitConfigDialog.py\
			 gui/pyarchinitInfoDialog.py\
			 gui/quantpanelmain.py\
			 gui/sortpanelmain.py\
			 gui/ui/mplwidget.py\
			 gui/ui/mplwidgetmatrix.py\
			 modules/utility/__init__.py\
			 modules/utility/csv_writer.py\
			 modules/utility/delegateComboBox.py\
			 modules/utility/githubtest.py\
			 modules/utility/media_poderata_sperimentale.py\
			 modules/utility/media_ponderata_sperimentale.py\
			 modules/utility/mplwidget.py\
			 modules/utility/print_relazione_pdf.py\
			 modules/utility/pyarchinit_backup_dir.py\
			 modules/utility/pyarchinit_error_check.py\
			 modules/utility/pyarchinit_exp_Campsheet_pdf.py\
			 modules/utility/pyarchinit_exp_Documentazionesheet_pdf.py\
			 modules/utility/pyarchinit_exp_Findssheet_pdf.py\
			 modules/utility/pyarchinit_exp_Individui_pdf.py\
			 modules/utility/pyarchinit_exp_Invlapsheet_pdf.py\
			 modules/utility/pyarchinit_exp_pdf_experimental.py\
			 modules/utility/pyarchinit_exp_pdf_utility.py\
			 modules/utility/pyarchinit_exp_Periodizzazionesheet_pdf.py\
			 modules/utility/pyarchinit_exp_Periodosheet_pdf.py\
			 modules/utility/pyarchinit_exp_Strutturasheet_pdf.py\
			 modules/utility/pyarchinit_exp_Tafonomiasheet_pdf.py\
			 modules/utility/pyarchinit_exp_USsheet_pdf.py\
			 modules/utility/pyarchinit_exp_UTsheet_pdf.py\
			 modules/utility/pyarchinit_folder_installation.py\
			 modules/utility/pyarchinit_matrix_exp.py\
			 modules/utility/pyarchinit_media_utility.py\
			 modules/utility/pyarchinit_OS_utility.py\
			 modules/utility/pyarchinit_print_utility.py\
			 modules/utility/settings.py\
			 modules/utility/test_dirname.py\
			 modules/utility/testtable_checkbox.py			

FORMS =   	gui/ui/Archeozoology.ui\
			gui/ui/Campioni.ui\
			gui/ui/dbmanagment.ui\
			gui/ui/Deteta.ui\
			gui/ui/Detsesso.ui\
			gui/ui/Documentazione.ui\
			gui/ui/Documentazione_preview.ui\
			gui/ui/Gis_Time_controller.ui\
			gui/ui/Image_Viewer.ui\
			gui/ui/Images_comparison.ui\
			gui/ui/Images_directory_export.ui\
			gui/ui/Interactive_matrix.ui\
			gui/ui/Inv_Lapidei.ui\
			gui/ui/Inv_Materiali.ui\
			gui/ui/Pdf_administrator.ui\
			gui/ui/Pdf_export.ui\
			gui/ui/Periodizzazione.ui\
			gui/ui/pyarchinit_directory_creator_ui.ui\
			gui/ui/pyarchinit_image_viewer_dialog.ui\
			gui/ui/pyarchinit_images_export_ui.ui\
			gui/ui/pyarchinit_plugin.ui\
			gui/ui/pyarchinit_rel_check_ui.ui\
			gui/ui/pyarchinitConfigDialog.ui\
			gui/ui/pyarchinitInfoDialog.ui\
			gui/ui/quantpanelmain.ui\
			gui/ui/Schedaind.ui\
			gui/ui/Site.ui\
			gui/ui/sortpanelmain.ui\
			gui/ui/Struttura.ui\
			gui/ui/Tafonomia.ui\
			gui/ui/Thesaurus.ui\
			gui/ui/Upd.ui\
			gui/ui/US_USM.ui\
			gui/ui/UT_ui.ui

TRANSLATIONS = i18n/pyarchinit_plugin_it_IT.ts \
               i18n/pyarchinit_plugin_de_DE.ts \
               i18n/pyarchinit_plugin_en_US.ts 