# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyarchinit_Tafonomia_ui.ui'
#
# Created: Thu Aug 21 15:06:33 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import resources_rc


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog_tafonomia(object):
    def setupUi(self, Dialog_tafonomia):
        Dialog_tafonomia.setObjectName(_fromUtf8("Dialog_tafonomia"))
        Dialog_tafonomia.resize(576, 604)
        Dialog_tafonomia.setMinimumSize(QtCore.QSize(540, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/iconGrave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_tafonomia.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(Dialog_tafonomia)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_45 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_7.addWidget(self.label_45, 0, 0, 1, 1)
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.pushButton_first_rec = QtGui.QPushButton(Dialog_tafonomia)
        self.pushButton_first_rec.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/5_leftArrows.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_first_rec.setIcon(icon1)
        self.pushButton_first_rec.setObjectName(_fromUtf8("pushButton_first_rec"))
        self.gridLayout_16.addWidget(self.pushButton_first_rec, 0, 5, 1, 1)
        self.pushButton_next_rec = QtGui.QPushButton(Dialog_tafonomia)
        self.pushButton_next_rec.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/6_rightArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_rec.setIcon(icon2)
        self.pushButton_next_rec.setObjectName(_fromUtf8("pushButton_next_rec"))
        self.gridLayout_16.addWidget(self.pushButton_next_rec, 0, 7, 1, 1)
        self.pushButton_last_rec = QtGui.QPushButton(Dialog_tafonomia)
        self.pushButton_last_rec.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/7_rightArrows.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last_rec.setIcon(icon3)
        self.pushButton_last_rec.setObjectName(_fromUtf8("pushButton_last_rec"))
        self.gridLayout_16.addWidget(self.pushButton_last_rec, 0, 8, 1, 1)
        self.pushButton_new_rec = QtGui.QPushButton(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_rec.setFont(font)
        self.pushButton_new_rec.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/newrec.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_rec.setIcon(icon4)
        self.pushButton_new_rec.setObjectName(_fromUtf8("pushButton_new_rec"))
        self.gridLayout_16.addWidget(self.pushButton_new_rec, 0, 9, 1, 1)
        self.pushButton_save = QtGui.QPushButton(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/b_save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon5)
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.gridLayout_16.addWidget(self.pushButton_save, 0, 10, 1, 1)
        self.pushButton_new_search = QtGui.QPushButton(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_search.setFont(font)
        self.pushButton_new_search.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/new_search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_search.setIcon(icon6)
        self.pushButton_new_search.setObjectName(_fromUtf8("pushButton_new_search"))
        self.gridLayout_16.addWidget(self.pushButton_new_search, 1, 7, 1, 1)
        self.pushButton_search_go = QtGui.QPushButton(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_search_go.setFont(font)
        self.pushButton_search_go.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search_go.setIcon(icon7)
        self.pushButton_search_go.setObjectName(_fromUtf8("pushButton_search_go"))
        self.gridLayout_16.addWidget(self.pushButton_search_go, 1, 8, 1, 1)
        self.pushButton_sort = QtGui.QPushButton(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_sort.setFont(font)
        self.pushButton_sort.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/sort.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sort.setIcon(icon8)
        self.pushButton_sort.setObjectName(_fromUtf8("pushButton_sort"))
        self.gridLayout_16.addWidget(self.pushButton_sort, 1, 9, 1, 1)
        self.pushButton_view_all = QtGui.QPushButton(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_view_all.setFont(font)
        self.pushButton_view_all.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/view_all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_view_all.setIcon(icon9)
        self.pushButton_view_all.setObjectName(_fromUtf8("pushButton_view_all"))
        self.gridLayout_16.addWidget(self.pushButton_view_all, 1, 10, 1, 1)
        self.pushButton_delete = QtGui.QPushButton(Dialog_tafonomia)
        self.pushButton_delete.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon10)
        self.pushButton_delete.setObjectName(_fromUtf8("pushButton_delete"))
        self.gridLayout_16.addWidget(self.pushButton_delete, 1, 2, 1, 1)
        self.pushButton_prev_rec = QtGui.QPushButton(Dialog_tafonomia)
        self.pushButton_prev_rec.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/4_leftArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prev_rec.setIcon(icon11)
        self.pushButton_prev_rec.setObjectName(_fromUtf8("pushButton_prev_rec"))
        self.gridLayout_16.addWidget(self.pushButton_prev_rec, 0, 6, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_16, 2, 0, 1, 2)
        self.pushButton_connect = QtGui.QPushButton(Dialog_tafonomia)
        self.pushButton_connect.setObjectName(_fromUtf8("pushButton_connect"))
        self.gridLayout_7.addWidget(self.pushButton_connect, 1, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_7)
        self.line_7 = QtGui.QFrame(Dialog_tafonomia)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout_3.addWidget(self.line_7)
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.label_46 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_46.setFont(font)
        self.label_46.setAutoFillBackground(True)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_17.addWidget(self.label_46, 0, 0, 1, 1)
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.label_48 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_48.setFont(font)
        self.label_48.setMargin(0)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_18.addWidget(self.label_48, 0, 1, 1, 1)
        self.label_status_2 = QtGui.QLabel(Dialog_tafonomia)
        self.label_status_2.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_status_2.setFont(font)
        self.label_status_2.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_status_2.setMouseTracking(False)
        self.label_status_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_status_2.setFrameShape(QtGui.QFrame.Box)
        self.label_status_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_status_2.setText(_fromUtf8(""))
        self.label_status_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_2.setMargin(0)
        self.label_status_2.setObjectName(_fromUtf8("label_status_2"))
        self.gridLayout_18.addWidget(self.label_status_2, 1, 0, 1, 1)
        self.label_sort_2 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_sort_2.setFont(font)
        self.label_sort_2.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_sort_2.setMouseTracking(False)
        self.label_sort_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_sort_2.setFrameShape(QtGui.QFrame.Box)
        self.label_sort_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sort_2.setText(_fromUtf8(""))
        self.label_sort_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sort_2.setMargin(0)
        self.label_sort_2.setObjectName(_fromUtf8("label_sort_2"))
        self.gridLayout_18.addWidget(self.label_sort_2, 1, 1, 1, 1)
        self.label_49 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_49.setFont(font)
        self.label_49.setMargin(0)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_18.addWidget(self.label_49, 0, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_18, 1, 0, 1, 1)
        self.gridLayout_19 = QtGui.QGridLayout()
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.label_50 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_50.setFont(font)
        self.label_50.setMargin(0)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_19.addWidget(self.label_50, 0, 0, 1, 1)
        self.label_rec_corrente_2 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft Sans Serif"))
        font.setPointSize(12)
        self.label_rec_corrente_2.setFont(font)
        self.label_rec_corrente_2.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_corrente_2.setMouseTracking(False)
        self.label_rec_corrente_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_corrente_2.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_corrente_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_corrente_2.setObjectName(_fromUtf8("label_rec_corrente_2"))
        self.gridLayout_19.addWidget(self.label_rec_corrente_2, 0, 1, 1, 1)
        self.label_51 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_51.setFont(font)
        self.label_51.setMargin(0)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_19.addWidget(self.label_51, 1, 0, 1, 1)
        self.label_rec_tot_2 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft Sans Serif"))
        font.setPointSize(12)
        self.label_rec_tot_2.setFont(font)
        self.label_rec_tot_2.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_tot_2.setMouseTracking(False)
        self.label_rec_tot_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_tot_2.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_tot_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_tot_2.setObjectName(_fromUtf8("label_rec_tot_2"))
        self.gridLayout_19.addWidget(self.label_rec_tot_2, 1, 1, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_19, 2, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_17)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 3)
        self.line_8 = QtGui.QFrame(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout.addWidget(self.line_8, 1, 0, 1, 3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(Dialog_tafonomia)
        self.label.setMaximumSize(QtCore.QSize(28, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_sito = QtGui.QComboBox(Dialog_tafonomia)
        self.comboBox_sito.setEnabled(False)
        self.comboBox_sito.setMinimumSize(QtCore.QSize(361, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_sito.setFont(font)
        self.comboBox_sito.setMouseTracking(True)
        self.comboBox_sito.setEditable(True)
        self.comboBox_sito.setMaxVisibleItems(99999)
        self.comboBox_sito.setMaxCount(2147483647)
        self.comboBox_sito.setObjectName(_fromUtf8("comboBox_sito"))
        self.comboBox_sito.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox_sito)
        self.label_2 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_nr_scheda = QtGui.QLineEdit(Dialog_tafonomia)
        self.lineEdit_nr_scheda.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_nr_scheda.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_nr_scheda.setObjectName(_fromUtf8("lineEdit_nr_scheda"))
        self.horizontalLayout.addWidget(self.lineEdit_nr_scheda)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_32 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_5.addWidget(self.label_32)
        self.comboBox_sigla_struttura = QtGui.QComboBox(Dialog_tafonomia)
        self.comboBox_sigla_struttura.setEnabled(False)
        self.comboBox_sigla_struttura.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_sigla_struttura.setMaximumSize(QtCore.QSize(60, 22))
        self.comboBox_sigla_struttura.setEditable(True)
        self.comboBox_sigla_struttura.setObjectName(_fromUtf8("comboBox_sigla_struttura"))
        self.horizontalLayout_5.addWidget(self.comboBox_sigla_struttura)
        self.comboBox_nr_struttura = QtGui.QComboBox(Dialog_tafonomia)
        self.comboBox_nr_struttura.setEnabled(False)
        self.comboBox_nr_struttura.setMinimumSize(QtCore.QSize(60, 0))
        self.comboBox_nr_struttura.setMaximumSize(QtCore.QSize(60, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_nr_struttura.setFont(font)
        self.comboBox_nr_struttura.setEditable(True)
        self.comboBox_nr_struttura.setObjectName(_fromUtf8("comboBox_nr_struttura"))
        self.horizontalLayout_5.addWidget(self.comboBox_nr_struttura)
        spacerItem = QtGui.QSpacerItem(178, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_19 = QtGui.QLabel(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_5.addWidget(self.label_19)
        self.comboBox_nr_individuo = QtGui.QComboBox(Dialog_tafonomia)
        self.comboBox_nr_individuo.setEnabled(False)
        self.comboBox_nr_individuo.setMinimumSize(QtCore.QSize(0, 22))
        self.comboBox_nr_individuo.setMaximumSize(QtCore.QSize(16777215, 22))
        self.comboBox_nr_individuo.setEditable(True)
        self.comboBox_nr_individuo.setObjectName(_fromUtf8("comboBox_nr_individuo"))
        self.horizontalLayout_5.addWidget(self.comboBox_nr_individuo)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 3)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tabWidget = QtGui.QTabWidget(Dialog_tafonomia)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tab)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_3 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_9.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboBox_segnacoli = QtGui.QComboBox(self.tab)
        self.comboBox_segnacoli.setMinimumSize(QtCore.QSize(0, 19))
        self.comboBox_segnacoli.setEditable(True)
        self.comboBox_segnacoli.setObjectName(_fromUtf8("comboBox_segnacoli"))
        self.comboBox_segnacoli.addItem(_fromUtf8(""))
        self.comboBox_segnacoli.setItemText(0, _fromUtf8(""))
        self.comboBox_segnacoli.addItem(_fromUtf8(""))
        self.comboBox_segnacoli.addItem(_fromUtf8(""))
        self.comboBox_segnacoli.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.comboBox_segnacoli, 0, 1, 1, 1)
        self.comboBox_canale_libatorio = QtGui.QComboBox(self.tab)
        self.comboBox_canale_libatorio.setMinimumSize(QtCore.QSize(100, 19))
        self.comboBox_canale_libatorio.setEditable(True)
        self.comboBox_canale_libatorio.setObjectName(_fromUtf8("comboBox_canale_libatorio"))
        self.comboBox_canale_libatorio.addItem(_fromUtf8(""))
        self.comboBox_canale_libatorio.setItemText(0, _fromUtf8(""))
        self.comboBox_canale_libatorio.addItem(_fromUtf8(""))
        self.comboBox_canale_libatorio.addItem(_fromUtf8(""))
        self.comboBox_canale_libatorio.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.comboBox_canale_libatorio, 0, 2, 1, 1)
        self.comboBox_oggetti_esterno = QtGui.QComboBox(self.tab)
        self.comboBox_oggetti_esterno.setMinimumSize(QtCore.QSize(0, 19))
        self.comboBox_oggetti_esterno.setEditable(True)
        self.comboBox_oggetti_esterno.setObjectName(_fromUtf8("comboBox_oggetti_esterno"))
        self.comboBox_oggetti_esterno.addItem(_fromUtf8(""))
        self.comboBox_oggetti_esterno.setItemText(0, _fromUtf8(""))
        self.comboBox_oggetti_esterno.addItem(_fromUtf8(""))
        self.comboBox_oggetti_esterno.addItem(_fromUtf8(""))
        self.comboBox_oggetti_esterno.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.comboBox_oggetti_esterno, 0, 3, 1, 1)
        self.label_30 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_9.addWidget(self.label_30, 1, 0, 1, 1)
        self.comboBox_conservazione_taf = QtGui.QComboBox(self.tab)
        self.comboBox_conservazione_taf.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_conservazione_taf.setFont(font)
        self.comboBox_conservazione_taf.setEditable(True)
        self.comboBox_conservazione_taf.setObjectName(_fromUtf8("comboBox_conservazione_taf"))
        self.comboBox_conservazione_taf.addItem(_fromUtf8(""))
        self.comboBox_conservazione_taf.addItem(_fromUtf8(""))
        self.comboBox_conservazione_taf.addItem(_fromUtf8(""))
        self.comboBox_conservazione_taf.addItem(_fromUtf8(""))
        self.comboBox_conservazione_taf.addItem(_fromUtf8(""))
        self.comboBox_conservazione_taf.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.comboBox_conservazione_taf, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_9.addWidget(self.label_8, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_9.addWidget(self.label_4, 1, 3, 1, 1)
        self.comboBox_copertura_tipo = QtGui.QComboBox(self.tab)
        self.comboBox_copertura_tipo.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_copertura_tipo.setFont(font)
        self.comboBox_copertura_tipo.setEditable(True)
        self.comboBox_copertura_tipo.setObjectName(_fromUtf8("comboBox_copertura_tipo"))
        self.comboBox_copertura_tipo.addItem(_fromUtf8(""))
        self.comboBox_copertura_tipo.addItem(_fromUtf8(""))
        self.comboBox_copertura_tipo.addItem(_fromUtf8(""))
        self.comboBox_copertura_tipo.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.comboBox_copertura_tipo, 2, 0, 1, 1)
        self.comboBox_tipo_contenitore_resti = QtGui.QComboBox(self.tab)
        self.comboBox_tipo_contenitore_resti.setMinimumSize(QtCore.QSize(0, 19))
        self.comboBox_tipo_contenitore_resti.setEditable(True)
        self.comboBox_tipo_contenitore_resti.setObjectName(_fromUtf8("comboBox_tipo_contenitore_resti"))
        self.comboBox_tipo_contenitore_resti.addItem(_fromUtf8(""))
        self.comboBox_tipo_contenitore_resti.addItem(_fromUtf8(""))
        self.comboBox_tipo_contenitore_resti.addItem(_fromUtf8(""))
        self.comboBox_tipo_contenitore_resti.addItem(_fromUtf8(""))
        self.comboBox_tipo_contenitore_resti.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.comboBox_tipo_contenitore_resti, 2, 1, 1, 1)
        self.label_85 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_85.setFont(font)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.gridLayout_9.addWidget(self.label_85, 3, 0, 1, 1)
        self.label_35 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_9.addWidget(self.label_35, 3, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_9.addWidget(self.label_15, 4, 0, 1, 1)
        self.lineEdit_orientamento_asse = QtGui.QLineEdit(self.tab)
        self.lineEdit_orientamento_asse.setMinimumSize(QtCore.QSize(0, 19))
        self.lineEdit_orientamento_asse.setObjectName(_fromUtf8("lineEdit_orientamento_asse"))
        self.gridLayout_9.addWidget(self.lineEdit_orientamento_asse, 5, 0, 1, 1)
        self.lineEdit_orientamento_azimut = QtGui.QLineEdit(self.tab)
        self.lineEdit_orientamento_azimut.setMinimumSize(QtCore.QSize(0, 19))
        self.lineEdit_orientamento_azimut.setObjectName(_fromUtf8("lineEdit_orientamento_azimut"))
        self.gridLayout_9.addWidget(self.lineEdit_orientamento_azimut, 5, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_9.addWidget(self.label_31, 6, 0, 1, 1)
        self.label_47 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_9.addWidget(self.label_47, 6, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_9, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_14.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_10.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_10.addWidget(self.label_7, 0, 1, 1, 1)
        self.textEdit_descrizione_taf = QtGui.QTextEdit(self.tab)
        self.textEdit_descrizione_taf.setMinimumSize(QtCore.QSize(50, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_descrizione_taf.setFont(font)
        self.textEdit_descrizione_taf.setObjectName(_fromUtf8("textEdit_descrizione_taf"))
        self.gridLayout_10.addWidget(self.textEdit_descrizione_taf, 1, 0, 1, 1)
        self.textEdit_interpretazione_taf = QtGui.QTextEdit(self.tab)
        self.textEdit_interpretazione_taf.setMinimumSize(QtCore.QSize(250, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_interpretazione_taf.setFont(font)
        self.textEdit_interpretazione_taf.setObjectName(_fromUtf8("textEdit_interpretazione_taf"))
        self.gridLayout_10.addWidget(self.textEdit_interpretazione_taf, 1, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_10, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_17 = QtGui.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_11.addWidget(self.label_17, 0, 0, 1, 2)
        self.comboBox_corredo_presenza = QtGui.QComboBox(self.tab_5)
        self.comboBox_corredo_presenza.setEditable(True)
        self.comboBox_corredo_presenza.setObjectName(_fromUtf8("comboBox_corredo_presenza"))
        self.comboBox_corredo_presenza.addItem(_fromUtf8(""))
        self.comboBox_corredo_presenza.addItem(_fromUtf8(""))
        self.comboBox_corredo_presenza.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.comboBox_corredo_presenza, 1, 0, 1, 3)
        self.tableWidget_corredo_tipo = QtGui.QTableWidget(self.tab_5)
        self.tableWidget_corredo_tipo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_corredo_tipo.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_corredo_tipo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_corredo_tipo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_corredo_tipo.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_corredo_tipo.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_corredo_tipo.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_corredo_tipo.setRowCount(1)
        self.tableWidget_corredo_tipo.setColumnCount(3)
        self.tableWidget_corredo_tipo.setObjectName(_fromUtf8("tableWidget_corredo_tipo"))
        self.tableWidget_corredo_tipo.setColumnCount(3)
        self.tableWidget_corredo_tipo.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_corredo_tipo.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_corredo_tipo.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_corredo_tipo.setHorizontalHeaderItem(2, item)
        self.gridLayout_11.addWidget(self.tableWidget_corredo_tipo, 2, 0, 1, 3)
        self.pushButton_insert_row_corredo = QtGui.QPushButton(self.tab_5)
        self.pushButton_insert_row_corredo.setObjectName(_fromUtf8("pushButton_insert_row_corredo"))
        self.gridLayout_11.addWidget(self.pushButton_insert_row_corredo, 3, 0, 1, 1)
        self.pushButton_remove_row_corredo = QtGui.QPushButton(self.tab_5)
        self.pushButton_remove_row_corredo.setObjectName(_fromUtf8("pushButton_remove_row_corredo"))
        self.gridLayout_11.addWidget(self.pushButton_remove_row_corredo, 3, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(490, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem1, 3, 2, 1, 1)
        self.textEdit_descrizione_corredo = QtGui.QTextEdit(self.tab_5)
        self.textEdit_descrizione_corredo.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_descrizione_corredo.setFont(font)
        self.textEdit_descrizione_corredo.setObjectName(_fromUtf8("textEdit_descrizione_corredo"))
        self.gridLayout_11.addWidget(self.textEdit_descrizione_corredo, 4, 0, 1, 3)
        self.label_9 = QtGui.QLabel(self.tab_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_11.addWidget(self.label_9, 5, 0, 1, 2)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.lineEdit_lunghezza_scheletro = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_lunghezza_scheletro.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_lunghezza_scheletro.setFont(font)
        self.lineEdit_lunghezza_scheletro.setObjectName(_fromUtf8("lineEdit_lunghezza_scheletro"))
        self.gridLayout_15.addWidget(self.lineEdit_lunghezza_scheletro, 0, 0, 1, 1)
        self.comboBox_posizione_scheletro = QtGui.QComboBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_posizione_scheletro.setFont(font)
        self.comboBox_posizione_scheletro.setEditable(True)
        self.comboBox_posizione_scheletro.setObjectName(_fromUtf8("comboBox_posizione_scheletro"))
        self.comboBox_posizione_scheletro.addItem(_fromUtf8(""))
        self.comboBox_posizione_scheletro.setItemText(0, _fromUtf8(""))
        self.comboBox_posizione_scheletro.addItem(_fromUtf8(""))
        self.comboBox_posizione_scheletro.addItem(_fromUtf8(""))
        self.comboBox_posizione_scheletro.addItem(_fromUtf8(""))
        self.comboBox_posizione_scheletro.addItem(_fromUtf8(""))
        self.comboBox_posizione_scheletro.addItem(_fromUtf8(""))
        self.comboBox_posizione_scheletro.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.comboBox_posizione_scheletro, 0, 1, 1, 1)
        self.comboBox_posizione_cranio = QtGui.QComboBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_posizione_cranio.setFont(font)
        self.comboBox_posizione_cranio.setEditable(True)
        self.comboBox_posizione_cranio.setObjectName(_fromUtf8("comboBox_posizione_cranio"))
        self.comboBox_posizione_cranio.addItem(_fromUtf8(""))
        self.comboBox_posizione_cranio.setItemText(0, _fromUtf8(""))
        self.comboBox_posizione_cranio.addItem(_fromUtf8(""))
        self.comboBox_posizione_cranio.addItem(_fromUtf8(""))
        self.comboBox_posizione_cranio.addItem(_fromUtf8(""))
        self.comboBox_posizione_cranio.addItem(_fromUtf8(""))
        self.comboBox_posizione_cranio.addItem(_fromUtf8(""))
        self.comboBox_posizione_cranio.addItem(_fromUtf8(""))
        self.comboBox_posizione_cranio.addItem(_fromUtf8(""))
        self.comboBox_posizione_cranio.addItem(_fromUtf8(""))
        self.comboBox_posizione_cranio.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.comboBox_posizione_cranio, 0, 2, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_15.addWidget(self.label_33, 1, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_15.addWidget(self.label_37, 1, 1, 1, 1)
        self.label_86 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_86.setFont(font)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.gridLayout_15.addWidget(self.label_86, 1, 2, 1, 1)
        self.comboBox_arti_superiori = QtGui.QComboBox(self.tab_2)
        self.comboBox_arti_superiori.setEditable(True)
        self.comboBox_arti_superiori.setObjectName(_fromUtf8("comboBox_arti_superiori"))
        self.comboBox_arti_superiori.addItem(_fromUtf8(""))
        self.comboBox_arti_superiori.setItemText(0, _fromUtf8(""))
        self.comboBox_arti_superiori.addItem(_fromUtf8(""))
        self.comboBox_arti_superiori.addItem(_fromUtf8(""))
        self.comboBox_arti_superiori.addItem(_fromUtf8(""))
        self.comboBox_arti_superiori.addItem(_fromUtf8(""))
        self.comboBox_arti_superiori.addItem(_fromUtf8(""))
        self.comboBox_arti_superiori.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.comboBox_arti_superiori, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_15.addWidget(self.label_5, 3, 0, 1, 1)
        self.comboBox_arti_inferiori = QtGui.QComboBox(self.tab_2)
        self.comboBox_arti_inferiori.setEditable(True)
        self.comboBox_arti_inferiori.setObjectName(_fromUtf8("comboBox_arti_inferiori"))
        self.comboBox_arti_inferiori.addItem(_fromUtf8(""))
        self.comboBox_arti_inferiori.setItemText(0, _fromUtf8(""))
        self.comboBox_arti_inferiori.addItem(_fromUtf8(""))
        self.comboBox_arti_inferiori.addItem(_fromUtf8(""))
        self.comboBox_arti_inferiori.addItem(_fromUtf8(""))
        self.comboBox_arti_inferiori.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.comboBox_arti_inferiori, 4, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_15.addWidget(self.label_10, 5, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem2, 6, 1, 1, 1)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_11 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_12.addWidget(self.label_11, 0, 0, 1, 1)
        self.comboBox_disturbato = QtGui.QComboBox(self.tab_2)
        self.comboBox_disturbato.setMinimumSize(QtCore.QSize(45, 0))
        self.comboBox_disturbato.setMaximumSize(QtCore.QSize(20, 16777215))
        self.comboBox_disturbato.setEditable(True)
        self.comboBox_disturbato.setObjectName(_fromUtf8("comboBox_disturbato"))
        self.comboBox_disturbato.addItem(_fromUtf8(""))
        self.comboBox_disturbato.addItem(_fromUtf8(""))
        self.comboBox_disturbato.addItem(_fromUtf8(""))
        self.comboBox_disturbato.setItemText(2, _fromUtf8(""))
        self.gridLayout_12.addWidget(self.comboBox_disturbato, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_12.addWidget(self.label_12, 1, 0, 1, 1)
        self.comboBox_completo = QtGui.QComboBox(self.tab_2)
        self.comboBox_completo.setMinimumSize(QtCore.QSize(45, 0))
        self.comboBox_completo.setMaximumSize(QtCore.QSize(20, 16777215))
        self.comboBox_completo.setEditable(True)
        self.comboBox_completo.setObjectName(_fromUtf8("comboBox_completo"))
        self.comboBox_completo.addItem(_fromUtf8(""))
        self.comboBox_completo.addItem(_fromUtf8(""))
        self.comboBox_completo.addItem(_fromUtf8(""))
        self.comboBox_completo.setItemText(2, _fromUtf8(""))
        self.gridLayout_12.addWidget(self.comboBox_completo, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_12.addWidget(self.label_14, 2, 0, 1, 1)
        self.comboBox_in_connessione = QtGui.QComboBox(self.tab_2)
        self.comboBox_in_connessione.setMinimumSize(QtCore.QSize(45, 0))
        self.comboBox_in_connessione.setMaximumSize(QtCore.QSize(20, 16777215))
        self.comboBox_in_connessione.setEditable(True)
        self.comboBox_in_connessione.setFrame(True)
        self.comboBox_in_connessione.setObjectName(_fromUtf8("comboBox_in_connessione"))
        self.comboBox_in_connessione.addItem(_fromUtf8(""))
        self.comboBox_in_connessione.addItem(_fromUtf8(""))
        self.comboBox_in_connessione.addItem(_fromUtf8(""))
        self.comboBox_in_connessione.setItemText(2, _fromUtf8(""))
        self.gridLayout_12.addWidget(self.comboBox_in_connessione, 2, 1, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_12, 2, 1, 4, 2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.formLayout = QtGui.QFormLayout(self.tab_6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_insert_row_misure = QtGui.QPushButton(self.tab_6)
        self.pushButton_insert_row_misure.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_misure.setFont(font)
        self.pushButton_insert_row_misure.setObjectName(_fromUtf8("pushButton_insert_row_misure"))
        self.horizontalLayout_4.addWidget(self.pushButton_insert_row_misure)
        self.pushButton_remove_row_misure = QtGui.QPushButton(self.tab_6)
        self.pushButton_remove_row_misure.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButton_remove_row_misure.setObjectName(_fromUtf8("pushButton_remove_row_misure"))
        self.horizontalLayout_4.addWidget(self.pushButton_remove_row_misure)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.horizontalLayout_4)
        spacerItem3 = QtGui.QSpacerItem(329, 23, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout.setItem(0, QtGui.QFormLayout.FieldRole, spacerItem3)
        self.tableWidget_misurazioni = QtGui.QTableWidget(self.tab_6)
        self.tableWidget_misurazioni.setMinimumSize(QtCore.QSize(0, 280))
        self.tableWidget_misurazioni.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_misurazioni.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_misurazioni.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_misurazioni.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_misurazioni.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_misurazioni.setRowCount(1)
        self.tableWidget_misurazioni.setColumnCount(3)
        self.tableWidget_misurazioni.setObjectName(_fromUtf8("tableWidget_misurazioni"))
        self.tableWidget_misurazioni.setColumnCount(3)
        self.tableWidget_misurazioni.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_misurazioni.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_misurazioni.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_misurazioni.setHorizontalHeaderItem(2, item)
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.tableWidget_misurazioni)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.label_13 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_20.addWidget(self.label_13, 0, 0, 1, 4)
        self.label_42 = QtGui.QLabel(self.tab_7)
        self.label_42.setMinimumSize(QtCore.QSize(0, 15))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_20.addWidget(self.label_42, 1, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_7)
        self.label_16.setMinimumSize(QtCore.QSize(0, 15))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_20.addWidget(self.label_16, 1, 3, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_7)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_20.addWidget(self.label_21, 4, 3, 1, 1)
        self.label_34 = QtGui.QLabel(self.tab_7)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_20.addWidget(self.label_34, 4, 4, 1, 1)
        self.comboBox_fas_iniz = QtGui.QComboBox(self.tab_7)
        self.comboBox_fas_iniz.setObjectName(_fromUtf8("comboBox_fas_iniz"))
        self.gridLayout_20.addWidget(self.comboBox_fas_iniz, 3, 1, 1, 1)
        self.comboBox_per_fin = QtGui.QComboBox(self.tab_7)
        self.comboBox_per_fin.setObjectName(_fromUtf8("comboBox_per_fin"))
        self.gridLayout_20.addWidget(self.comboBox_per_fin, 3, 3, 1, 1)
        self.comboBox_fas_fin = QtGui.QComboBox(self.tab_7)
        self.comboBox_fas_fin.setObjectName(_fromUtf8("comboBox_fas_fin"))
        self.gridLayout_20.addWidget(self.comboBox_fas_fin, 3, 4, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab_7)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_20.addWidget(self.label_22, 4, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_7)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_20.addWidget(self.label_24, 4, 0, 1, 1)
        self.comboBox_per_iniz = QtGui.QComboBox(self.tab_7)
        self.comboBox_per_iniz.setObjectName(_fromUtf8("comboBox_per_iniz"))
        self.gridLayout_20.addWidget(self.comboBox_per_iniz, 3, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_20, 0, 0, 1, 1)
        self.lineEdit_datazione_estesa = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_datazione_estesa.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_datazione_estesa.setObjectName(_fromUtf8("lineEdit_datazione_estesa"))
        self.gridLayout_3.addWidget(self.lineEdit_datazione_estesa, 1, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab_7)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 2, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 184, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_remove_row_caratteristiche = QtGui.QPushButton(self.tab_3)
        self.pushButton_remove_row_caratteristiche.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_remove_row_caratteristiche.setObjectName(_fromUtf8("pushButton_remove_row_caratteristiche"))
        self.gridLayout_2.addWidget(self.pushButton_remove_row_caratteristiche, 0, 0, 1, 1)
        self.pushButton_insert_row_caratteristiche = QtGui.QPushButton(self.tab_3)
        self.pushButton_insert_row_caratteristiche.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_caratteristiche.setFont(font)
        self.pushButton_insert_row_caratteristiche.setObjectName(_fromUtf8("pushButton_insert_row_caratteristiche"))
        self.gridLayout_2.addWidget(self.pushButton_insert_row_caratteristiche, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(346, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 2, 1, 1)
        self.tableWidget_caratteristiche = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_caratteristiche.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_caratteristiche.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_caratteristiche.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_caratteristiche.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_caratteristiche.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_caratteristiche.setRowCount(1)
        self.tableWidget_caratteristiche.setColumnCount(2)
        self.tableWidget_caratteristiche.setObjectName(_fromUtf8("tableWidget_caratteristiche"))
        self.tableWidget_caratteristiche.setColumnCount(2)
        self.tableWidget_caratteristiche.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_caratteristiche.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_caratteristiche.setHorizontalHeaderItem(1, item)
        self.gridLayout_2.addWidget(self.tableWidget_caratteristiche, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_38 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_6.addWidget(self.label_38)
        self.toolButtonGis = QtGui.QToolButton(self.tab_4)
        self.toolButtonGis.setEnabled(False)
        self.toolButtonGis.setMinimumSize(QtCore.QSize(109, 0))
        self.toolButtonGis.setToolTip(_fromUtf8(""))
        self.toolButtonGis.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/GIS.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonGis.setIcon(icon12)
        self.toolButtonGis.setCheckable(True)
        self.toolButtonGis.setChecked(False)
        self.toolButtonGis.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonGis.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonGis.setObjectName(_fromUtf8("toolButtonGis"))
        self.horizontalLayout_6.addWidget(self.toolButtonGis)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.gridLayout_8.addLayout(self.horizontalLayout_6, 1, 1, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_39 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_7.addWidget(self.label_39)
        self.toolButtonPreview = QtGui.QToolButton(self.tab_4)
        self.toolButtonPreview.setEnabled(False)
        self.toolButtonPreview.setToolTip(_fromUtf8(""))
        self.toolButtonPreview.setIcon(icon12)
        self.toolButtonPreview.setCheckable(True)
        self.toolButtonPreview.setChecked(False)
        self.toolButtonPreview.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonPreview.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonPreview.setObjectName(_fromUtf8("toolButtonPreview"))
        self.horizontalLayout_7.addWidget(self.toolButtonPreview)
        self.toolButtonPan = QtGui.QToolButton(self.tab_4)
        self.toolButtonPan.setEnabled(False)
        self.toolButtonPan.setMinimumSize(QtCore.QSize(109, 0))
        self.toolButtonPan.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionPan.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPan.setIcon(icon13)
        self.toolButtonPan.setCheckable(True)
        self.toolButtonPan.setChecked(False)
        self.toolButtonPan.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonPan.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonPan.setObjectName(_fromUtf8("toolButtonPan"))
        self.horizontalLayout_7.addWidget(self.toolButtonPan)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.gridLayout_8.addLayout(self.horizontalLayout_7, 2, 0, 1, 2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_44 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.horizontalLayout_10.addWidget(self.label_44)
        self.toolButtonPreviewMedia = QtGui.QToolButton(self.tab_4)
        self.toolButtonPreviewMedia.setEnabled(False)
        self.toolButtonPreviewMedia.setMinimumSize(QtCore.QSize(109, 0))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/photo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPreviewMedia.setIcon(icon14)
        self.toolButtonPreviewMedia.setCheckable(True)
        self.toolButtonPreviewMedia.setObjectName(_fromUtf8("toolButtonPreviewMedia"))
        self.horizontalLayout_10.addWidget(self.toolButtonPreviewMedia)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.gridLayout_8.addLayout(self.horizontalLayout_10, 5, 1, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_41 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.horizontalLayout_9.addWidget(self.label_41)
        self.pushButton_pdf_exp = QtGui.QPushButton(self.tab_4)
        self.pushButton_pdf_exp.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_pdf_exp.setFont(font)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/sheet.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_pdf_exp.setIcon(icon15)
        self.pushButton_pdf_exp.setObjectName(_fromUtf8("pushButton_pdf_exp"))
        self.horizontalLayout_9.addWidget(self.pushButton_pdf_exp)
        self.pushButton_exp_index = QtGui.QPushButton(self.tab_4)
        self.pushButton_exp_index.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_exp_index.setFont(font)
        self.pushButton_exp_index.setIcon(icon15)
        self.pushButton_exp_index.setObjectName(_fromUtf8("pushButton_exp_index"))
        self.horizontalLayout_9.addWidget(self.pushButton_exp_index)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.gridLayout_8.addLayout(self.horizontalLayout_9, 0, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_40 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_8.addWidget(self.label_40)
        self.pushButton_showSelectedFeatures = QtGui.QPushButton(self.tab_4)
        self.pushButton_showSelectedFeatures.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_showSelectedFeatures.setFont(font)
        self.pushButton_showSelectedFeatures.setIcon(icon15)
        self.pushButton_showSelectedFeatures.setObjectName(_fromUtf8("pushButton_showSelectedFeatures"))
        self.horizontalLayout_8.addWidget(self.pushButton_showSelectedFeatures)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.gridLayout_8.addLayout(self.horizontalLayout_8, 3, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem11, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_6, 7, 0, 1, 3)
        self.label_18 = QtGui.QLabel(Dialog_tafonomia)
        self.label_18.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 4, 0, 1, 1)
        self.comboBox_rito = QtGui.QComboBox(Dialog_tafonomia)
        self.comboBox_rito.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_rito.setFont(font)
        self.comboBox_rito.setEditable(True)
        self.comboBox_rito.setObjectName(_fromUtf8("comboBox_rito"))
        self.comboBox_rito.addItem(_fromUtf8(""))
        self.comboBox_rito.addItem(_fromUtf8(""))
        self.comboBox_rito.addItem(_fromUtf8(""))
        self.comboBox_rito.addItem(_fromUtf8(""))
        self.comboBox_rito.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_rito, 4, 1, 1, 1)

        self.retranslateUi(Dialog_tafonomia)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog_tafonomia)

    def retranslateUi(self, Dialog_tafonomia):
        Dialog_tafonomia.setWindowTitle(QtGui.QApplication.translate("Dialog_tafonomia", "pyArchInit Gestione Scavi - Scheda Tafonomica", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("Dialog_tafonomia", "DBMS Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_first_rec.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "First rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_next_rec.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Next rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_last_rec.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Last rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_rec.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "New record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_search.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "new search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_search_go.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "search !!!", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_sort.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Order by", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_view_all.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "View alls records", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_delete.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Delete record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_prev_rec.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Prev rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_connect.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Connection test", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("Dialog_tafonomia", "DB Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Ordinamento", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("Dialog_tafonomia", "record n.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_corrente_2.setText(QtGui.QApplication.translate("Dialog_tafonomia", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("Dialog_tafonomia", "record tot.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_tot_2.setText(QtGui.QApplication.translate("Dialog_tafonomia", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Sito ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sito.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Inserisci un valore", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Nr Scheda", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Rif. struttura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Nr Individuo        ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Segnacoli", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_segnacoli.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Si", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_segnacoli.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_segnacoli.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "Non determinabile", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_canale_libatorio.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Si", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_canale_libatorio.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_canale_libatorio.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "Non determinabile", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_oggetti_esterno.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Si", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_oggetti_esterno.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_oggetti_esterno.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "Non determinabile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Stato di conserv.", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione_taf.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Insufficiente", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione_taf.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Scarso", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione_taf.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "Sufficiente", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione_taf.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "Discreto", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione_taf.setItemText(4, QtGui.QApplication.translate("Dialog_tafonomia", "Buono", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_conservazione_taf.setItemText(5, QtGui.QApplication.translate("Dialog_tafonomia", "Ottimo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Canale libatorio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Ogg. rinv. all\'esterno", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_copertura_tipo.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Non rilevabile", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_copertura_tipo.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Copertura assente", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_copertura_tipo.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "Tegole alla cappuccina", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_copertura_tipo.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "In cassa", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_contenitore_resti.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Entro sudario", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_contenitore_resti.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "In cassa fittile", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_contenitore_resti.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "In cassa lignea", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_contenitore_resti.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "In urna litica", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_tipo_contenitore_resti.setItemText(4, QtGui.QApplication.translate("Dialog_tafonomia", "Nella terra", None, QtGui.QApplication.UnicodeUTF8))
        self.label_85.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Tipo copertura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Tipo contenitore resti", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Orientamento", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_orientamento_azimut.setText(QtGui.QApplication.translate("Dialog_tafonomia", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Asse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Azimut", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Descrizione ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Interpretazione ", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_descrizione_taf.setHtml(QtGui.QApplication.translate("Dialog_tafonomia", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:13pt;\"><br /></span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog_tafonomia", "Dati descrittivi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Corredo ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_corredo_presenza.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Corredo assente", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_corredo_presenza.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Corredo presente", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_corredo_presenza.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "Non determinabile", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_corredo_tipo.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_tafonomia", "Nr. reperto", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_corredo_tipo.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog_tafonomia", "Tipo di corredo", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_corredo_tipo.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog_tafonomia", "Descrizione", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_corredo.setText(QtGui.QApplication.translate("Dialog_tafonomia", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row_corredo.setText(QtGui.QApplication.translate("Dialog_tafonomia", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_descrizione_corredo.setHtml(QtGui.QApplication.translate("Dialog_tafonomia", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:13pt;\"><br /></span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Descrizione ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("Dialog_tafonomia", "Corredo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_scheletro.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Non determinabile", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_scheletro.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "Supino", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_scheletro.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "Prono", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_scheletro.setItemText(4, QtGui.QApplication.translate("Dialog_tafonomia", "Posizione fetale", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_scheletro.setItemText(5, QtGui.QApplication.translate("Dialog_tafonomia", "Su lato dx", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_scheletro.setItemText(6, QtGui.QApplication.translate("Dialog_tafonomia", "Su lato sx", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_cranio.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Non determinabile", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_cranio.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "Nord", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_cranio.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "Est", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_cranio.setItemText(4, QtGui.QApplication.translate("Dialog_tafonomia", "Ovest", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_cranio.setItemText(5, QtGui.QApplication.translate("Dialog_tafonomia", "Sud", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_cranio.setItemText(6, QtGui.QApplication.translate("Dialog_tafonomia", "Nord-Est", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_cranio.setItemText(7, QtGui.QApplication.translate("Dialog_tafonomia", "Nord-Ovest", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_cranio.setItemText(8, QtGui.QApplication.translate("Dialog_tafonomia", "Sud-Est", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_posizione_cranio.setItemText(9, QtGui.QApplication.translate("Dialog_tafonomia", "Sud-Ovest", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Lunghezza scheletro", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Posizione scheletro", None, QtGui.QApplication.UnicodeUTF8))
        self.label_86.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Posizione cranio", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_superiori.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Non determinabile", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_superiori.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "Braccia lungo il corpo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_superiori.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "Braccia Incrociate sul petto", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_superiori.setItemText(4, QtGui.QApplication.translate("Dialog_tafonomia", "Braccia Incrociate sul bacino", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_superiori.setItemText(5, QtGui.QApplication.translate("Dialog_tafonomia", "Mani congiunte sul petto", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_superiori.setItemText(6, QtGui.QApplication.translate("Dialog_tafonomia", "Mani congiunte sul bacino  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Posizione arti superiori", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_inferiori.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Distesi", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_inferiori.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "Incrociati", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_inferiori.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "Asimmetrici", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_arti_inferiori.setItemText(4, QtGui.QApplication.translate("Dialog_tafonomia", "Non determinabile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Posizione arti infeiori", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Disturbato", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_disturbato.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Si", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_disturbato.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Completo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_completo.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Si", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_completo.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog_tafonomia", "In connessione", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_in_connessione.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Si", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_in_connessione.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog_tafonomia", "Resti osteologici", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_misure.setText(QtGui.QApplication.translate("Dialog_tafonomia", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row_misure.setText(QtGui.QApplication.translate("Dialog_tafonomia", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_misurazioni.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_tafonomia", "Tipo misura", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_misurazioni.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog_tafonomia", "Unita\' di misura", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_misurazioni.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog_tafonomia", "Valore", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("Dialog_tafonomia", "Misure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Periodizzazione ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Iniziale ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Finale ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Periodo ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Fase ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Fase ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Periodo ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Datazione estesa", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QtGui.QApplication.translate("Dialog_tafonomia", "Periodizzazione", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row_caratteristiche.setText(QtGui.QApplication.translate("Dialog_tafonomia", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_insert_row_caratteristiche.setText(QtGui.QApplication.translate("Dialog_tafonomia", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_caratteristiche.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog_tafonomia", "Tipo caratteristica", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_caratteristiche.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog_tafonomia", "Posizione", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog_tafonomia", "Caratteristiche", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Visualizzazione GIS", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonGis.setShortcut(QtGui.QApplication.translate("Dialog_tafonomia", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Attivazione Preview pianta US", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPreview.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Preview pianta US", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPreview.setShortcut(QtGui.QApplication.translate("Dialog_tafonomia", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPan.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Pan tool", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPan.setShortcut(QtGui.QApplication.translate("Dialog_tafonomia", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Mostra immagini", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPreviewMedia.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Mostra immagini", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Esporta schede Tafonomiche in formato PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pdf_exp.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Export PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pdf_exp.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Singole schede", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_exp_index.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Elenco ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Apri schede US selezionate", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_showSelectedFeatures.setToolTip(QtGui.QApplication.translate("Dialog_tafonomia", "Show Selcted Features", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_showSelectedFeatures.setText(QtGui.QApplication.translate("Dialog_tafonomia", "apri schede US", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Dialog_tafonomia", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog_tafonomia", "Rito", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_rito.setItemText(0, QtGui.QApplication.translate("Dialog_tafonomia", "Riduzione", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_rito.setItemText(1, QtGui.QApplication.translate("Dialog_tafonomia", "Ad inumazione", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_rito.setItemText(2, QtGui.QApplication.translate("Dialog_tafonomia", "Ad incinerazione diretta", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_rito.setItemText(3, QtGui.QApplication.translate("Dialog_tafonomia", "Ad incinerazione indiretta", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_rito.setItemText(4, QtGui.QApplication.translate("Dialog_tafonomia", "Mummuficazione", None, QtGui.QApplication.UnicodeUTF8))

