# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyarchinit_Site_ui.ui'
#
# Created: Sun Dec 18 18:28:58 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogSite(object):
    def setupUi(self, DialogSite):
        DialogSite.setObjectName(_fromUtf8("DialogSite"))
        DialogSite.resize(622, 670)
        DialogSite.setMinimumSize(QtCore.QSize(540, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/iconSite.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogSite.setWindowIcon(icon)
        self.gridLayout_7 = QtGui.QGridLayout(DialogSite)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_29 = QtGui.QLabel(DialogSite)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_first_rec = QtGui.QPushButton(DialogSite)
        self.pushButton_first_rec.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/5_leftArrows.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_first_rec.setIcon(icon1)
        self.pushButton_first_rec.setObjectName(_fromUtf8("pushButton_first_rec"))
        self.gridLayout.addWidget(self.pushButton_first_rec, 0, 5, 1, 1)
        self.pushButton_next_rec = QtGui.QPushButton(DialogSite)
        self.pushButton_next_rec.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/6_rightArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_rec.setIcon(icon2)
        self.pushButton_next_rec.setObjectName(_fromUtf8("pushButton_next_rec"))
        self.gridLayout.addWidget(self.pushButton_next_rec, 0, 7, 1, 1)
        self.pushButton_last_rec = QtGui.QPushButton(DialogSite)
        self.pushButton_last_rec.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/7_rightArrows.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last_rec.setIcon(icon3)
        self.pushButton_last_rec.setObjectName(_fromUtf8("pushButton_last_rec"))
        self.gridLayout.addWidget(self.pushButton_last_rec, 0, 8, 1, 1)
        self.pushButton_new_rec = QtGui.QPushButton(DialogSite)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_rec.setFont(font)
        self.pushButton_new_rec.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/newrec.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_rec.setIcon(icon4)
        self.pushButton_new_rec.setObjectName(_fromUtf8("pushButton_new_rec"))
        self.gridLayout.addWidget(self.pushButton_new_rec, 0, 9, 1, 1)
        self.pushButton_save = QtGui.QPushButton(DialogSite)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/b_save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon5)
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.gridLayout.addWidget(self.pushButton_save, 0, 10, 1, 1)
        self.pushButton_new_search = QtGui.QPushButton(DialogSite)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_search.setFont(font)
        self.pushButton_new_search.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/new_search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_search.setIcon(icon6)
        self.pushButton_new_search.setObjectName(_fromUtf8("pushButton_new_search"))
        self.gridLayout.addWidget(self.pushButton_new_search, 1, 7, 1, 1)
        self.pushButton_search_go = QtGui.QPushButton(DialogSite)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_search_go.setFont(font)
        self.pushButton_search_go.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search_go.setIcon(icon7)
        self.pushButton_search_go.setObjectName(_fromUtf8("pushButton_search_go"))
        self.gridLayout.addWidget(self.pushButton_search_go, 1, 8, 1, 1)
        self.pushButton_sort = QtGui.QPushButton(DialogSite)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_sort.setFont(font)
        self.pushButton_sort.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/sort.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sort.setIcon(icon8)
        self.pushButton_sort.setObjectName(_fromUtf8("pushButton_sort"))
        self.gridLayout.addWidget(self.pushButton_sort, 1, 9, 1, 1)
        self.pushButton_view_all = QtGui.QPushButton(DialogSite)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_view_all.setFont(font)
        self.pushButton_view_all.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/view_all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_view_all.setIcon(icon9)
        self.pushButton_view_all.setObjectName(_fromUtf8("pushButton_view_all"))
        self.gridLayout.addWidget(self.pushButton_view_all, 1, 10, 1, 1)
        self.pushButton_delete = QtGui.QPushButton(DialogSite)
        self.pushButton_delete.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon10)
        self.pushButton_delete.setObjectName(_fromUtf8("pushButton_delete"))
        self.gridLayout.addWidget(self.pushButton_delete, 1, 2, 1, 1)
        self.pushButton_prev_rec = QtGui.QPushButton(DialogSite)
        self.pushButton_prev_rec.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/4_leftArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prev_rec.setIcon(icon11)
        self.pushButton_prev_rec.setObjectName(_fromUtf8("pushButton_prev_rec"))
        self.gridLayout.addWidget(self.pushButton_prev_rec, 0, 6, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 2)
        self.pushButton_connect = QtGui.QPushButton(DialogSite)
        self.pushButton_connect.setObjectName(_fromUtf8("pushButton_connect"))
        self.gridLayout_2.addWidget(self.pushButton_connect, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.line_6 = QtGui.QFrame(DialogSite)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout.addWidget(self.line_6)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_42 = QtGui.QLabel(DialogSite)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setAutoFillBackground(True)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_5.addWidget(self.label_42, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_43 = QtGui.QLabel(DialogSite)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setMargin(0)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_4.addWidget(self.label_43, 0, 1, 1, 1)
        self.label_status = QtGui.QLabel(DialogSite)
        self.label_status.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_status.setMouseTracking(False)
        self.label_status.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_status.setFrameShape(QtGui.QFrame.Box)
        self.label_status.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_status.setText(_fromUtf8(""))
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setMargin(0)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.gridLayout_4.addWidget(self.label_status, 1, 0, 1, 1)
        self.label_sort = QtGui.QLabel(DialogSite)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_sort.setFont(font)
        self.label_sort.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_sort.setMouseTracking(False)
        self.label_sort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_sort.setFrameShape(QtGui.QFrame.Box)
        self.label_sort.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sort.setText(_fromUtf8(""))
        self.label_sort.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sort.setMargin(0)
        self.label_sort.setObjectName(_fromUtf8("label_sort"))
        self.gridLayout_4.addWidget(self.label_sort, 1, 1, 1, 1)
        self.label_34 = QtGui.QLabel(DialogSite)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setMargin(0)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_4.addWidget(self.label_34, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_27 = QtGui.QLabel(DialogSite)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setMargin(0)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_3.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_rec_corrente = QtGui.QLabel(DialogSite)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft Sans Serif"))
        font.setPointSize(12)
        self.label_rec_corrente.setFont(font)
        self.label_rec_corrente.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_rec_corrente.setMouseTracking(False)
        self.label_rec_corrente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_corrente.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_corrente.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_corrente.setObjectName(_fromUtf8("label_rec_corrente"))
        self.gridLayout_3.addWidget(self.label_rec_corrente, 0, 1, 1, 1)
        self.label_28 = QtGui.QLabel(DialogSite)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setMargin(0)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_3.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_rec_tot = QtGui.QLabel(DialogSite)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft Sans Serif"))
        font.setPointSize(12)
        self.label_rec_tot.setFont(font)
        self.label_rec_tot.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_rec_tot.setMouseTracking(False)
        self.label_rec_tot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_tot.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_tot.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_tot.setObjectName(_fromUtf8("label_rec_tot"))
        self.gridLayout_3.addWidget(self.label_rec_tot, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.line_8 = QtGui.QFrame(DialogSite)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout.addWidget(self.line_8)
        self.comboBox_sito = QtGui.QComboBox(DialogSite)
        self.comboBox_sito.setEnabled(False)
        self.comboBox_sito.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_sito.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_sito.setFont(font)
        self.comboBox_sito.setMouseTracking(True)
        self.comboBox_sito.setEditable(True)
        self.comboBox_sito.setMaxVisibleItems(99999)
        self.comboBox_sito.setMaxCount(2147483647)
        self.comboBox_sito.setObjectName(_fromUtf8("comboBox_sito"))
        self.comboBox_sito.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.comboBox_sito)
        self.label = QtGui.QLabel(DialogSite)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.comboBox_definizione_sito = QtGui.QComboBox(DialogSite)
        self.comboBox_definizione_sito.setEnabled(True)
        self.comboBox_definizione_sito.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_definizione_sito.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_definizione_sito.setEditable(True)
        self.comboBox_definizione_sito.setObjectName(_fromUtf8("comboBox_definizione_sito"))
        self.verticalLayout.addWidget(self.comboBox_definizione_sito)
        self.tabWidget = QtGui.QTabWidget(DialogSite)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName(_fromUtf8("tabWidgetPage1"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabWidgetPage1)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_13 = QtGui.QLabel(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_3.addWidget(self.label_13)
        self.textEdit_descrizione_site = QtGui.QTextEdit(self.tabWidgetPage1)
        self.textEdit_descrizione_site.setMinimumSize(QtCore.QSize(0, 20))
        self.textEdit_descrizione_site.setMaximumSize(QtCore.QSize(16777215, 16000000))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_descrizione_site.setFont(font)
        self.textEdit_descrizione_site.setObjectName(_fromUtf8("textEdit_descrizione_site"))
        self.verticalLayout_3.addWidget(self.textEdit_descrizione_site)
        self.label_6 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.gridLayout_8.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.comboBox_nazione = QtGui.QComboBox(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_nazione.setFont(font)
        self.comboBox_nazione.setEditable(True)
        self.comboBox_nazione.setObjectName(_fromUtf8("comboBox_nazione"))
        self.comboBox_nazione.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBox_nazione, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 1, 0, 1, 1)
        self.comboBox_regione = QtGui.QComboBox(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_regione.setFont(font)
        self.comboBox_regione.setEditable(True)
        self.comboBox_regione.setObjectName(_fromUtf8("comboBox_regione"))
        self.gridLayout_6.addWidget(self.comboBox_regione, 0, 1, 1, 1)
        self.comboBox_comune = QtGui.QComboBox(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_comune.setFont(font)
        self.comboBox_comune.setEditable(True)
        self.comboBox_comune.setObjectName(_fromUtf8("comboBox_comune"))
        self.gridLayout_6.addWidget(self.comboBox_comune, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 3, 1, 1, 1)
        self.comboBox_provincia = QtGui.QComboBox(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_provincia.setFont(font)
        self.comboBox_provincia.setEditable(True)
        self.comboBox_provincia.setObjectName(_fromUtf8("comboBox_provincia"))
        self.gridLayout_6.addWidget(self.comboBox_provincia, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 1, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage1, _fromUtf8(""))
        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName(_fromUtf8("tabWidgetPage2"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tabWidgetPage2)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_8 = QtGui.QLabel(self.tabWidgetPage2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        self.pushButton_sites_geometry = QtGui.QPushButton(self.tabWidgetPage2)
        self.pushButton_sites_geometry.setObjectName(_fromUtf8("pushButton_sites_geometry"))
        self.horizontalLayout_3.addWidget(self.pushButton_sites_geometry)
        self.gridLayout_10.addLayout(self.horizontalLayout_3, 13, 0, 1, 5)
        self.label_14 = QtGui.QLabel(self.tabWidgetPage2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_10.addWidget(self.label_14, 1, 0, 1, 1)
        self.lineEdit_us_range = QtGui.QLineEdit(self.tabWidgetPage2)
        self.lineEdit_us_range.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_us_range.setObjectName(_fromUtf8("lineEdit_us_range"))
        self.gridLayout_10.addWidget(self.lineEdit_us_range, 3, 0, 1, 1)
        self.pushButton_genera_us = QtGui.QPushButton(self.tabWidgetPage2)
        self.pushButton_genera_us.setObjectName(_fromUtf8("pushButton_genera_us"))
        self.gridLayout_10.addWidget(self.pushButton_genera_us, 9, 0, 1, 1)
        self.lineEdit_area = QtGui.QLineEdit(self.tabWidgetPage2)
        self.lineEdit_area.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_area.setObjectName(_fromUtf8("lineEdit_area"))
        self.gridLayout_10.addWidget(self.lineEdit_area, 5, 0, 1, 1)
        self.lineEdit_n_us = QtGui.QLineEdit(self.tabWidgetPage2)
        self.lineEdit_n_us.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_n_us.setObjectName(_fromUtf8("lineEdit_n_us"))
        self.gridLayout_10.addWidget(self.lineEdit_n_us, 7, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.tabWidgetPage2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_10.addWidget(self.label_16, 6, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.tabWidgetPage2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_10.addWidget(self.label_15, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.tabWidgetPage2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.pushButton_draw = QtGui.QPushButton(self.tabWidgetPage2)
        self.pushButton_draw.setObjectName(_fromUtf8("pushButton_draw"))
        self.horizontalLayout_2.addWidget(self.pushButton_draw)
        self.gridLayout_10.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_9 = QtGui.QLabel(self.tabWidgetPage2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.pushButton_rel_pdf = QtGui.QPushButton(self.tabWidgetPage2)
        self.pushButton_rel_pdf.setObjectName(_fromUtf8("pushButton_rel_pdf"))
        self.horizontalLayout_4.addWidget(self.pushButton_rel_pdf)
        self.gridLayout_10.addLayout(self.horizontalLayout_4, 14, 0, 1, 7)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.line = QtGui.QFrame(self.tabWidgetPage2)
        self.line.setMinimumSize(QtCore.QSize(539, 0))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        self.label_10 = QtGui.QLabel(self.tabWidgetPage2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_4.addWidget(self.label_10)
        self.gridLayout_10.addLayout(self.verticalLayout_4, 15, 0, 1, 7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_12 = QtGui.QLabel(self.tabWidgetPage2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_6.addWidget(self.label_12)
        self.toolButton_draw_siti = QtGui.QToolButton(self.tabWidgetPage2)
        self.toolButton_draw_siti.setCheckable(True)
        self.toolButton_draw_siti.setObjectName(_fromUtf8("toolButton_draw_siti"))
        self.horizontalLayout_6.addWidget(self.toolButton_draw_siti)
        self.gridLayout_10.addLayout(self.horizontalLayout_6, 17, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_11 = QtGui.QLabel(self.tabWidgetPage2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_5.addWidget(self.label_11)
        self.pushButton_draw_sito = QtGui.QPushButton(self.tabWidgetPage2)
        self.pushButton_draw_sito.setObjectName(_fromUtf8("pushButton_draw_sito"))
        self.horizontalLayout_5.addWidget(self.pushButton_draw_sito)
        self.gridLayout_10.addLayout(self.horizontalLayout_5, 16, 0, 1, 5)
        spacerItem = QtGui.QSpacerItem(261, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem, 16, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(307, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem1, 17, 4, 1, 3)
        self.label_17 = QtGui.QLabel(self.tabWidgetPage2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_10.addWidget(self.label_17, 8, 0, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage2, _fromUtf8(""))
        self.tabWidgetPage3 = QtGui.QWidget()
        self.tabWidgetPage3.setObjectName(_fromUtf8("tabWidgetPage3"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tabWidgetPage3)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.pushButton_test = QtGui.QPushButton(self.tabWidgetPage3)
        self.pushButton_test.setObjectName(_fromUtf8("pushButton_test"))
        self.gridLayout_9.addWidget(self.pushButton_test, 0, 0, 1, 1)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tabWidgetPage3)
        self.plainTextEdit.setEnabled(False)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.gridLayout_9.addWidget(self.plainTextEdit, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage3, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(DialogSite)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogSite)

    def retranslateUi(self, DialogSite):
        DialogSite.setWindowTitle(_translate("DialogSite", "pyArchInit Gestione Scavi - Scheda Sito", None))
        self.label_29.setText(_translate("DialogSite", "DBMS Toolbar", None))
        self.pushButton_first_rec.setToolTip(_translate("DialogSite", "First rec", None))
        self.pushButton_next_rec.setToolTip(_translate("DialogSite", "Next rec", None))
        self.pushButton_last_rec.setToolTip(_translate("DialogSite", "Last rec", None))
        self.pushButton_new_rec.setToolTip(_translate("DialogSite", "New record", None))
        self.pushButton_save.setToolTip(_translate("DialogSite", "Save", None))
        self.pushButton_new_search.setToolTip(_translate("DialogSite", "new search", None))
        self.pushButton_search_go.setToolTip(_translate("DialogSite", "search !!!", None))
        self.pushButton_sort.setToolTip(_translate("DialogSite", "Order by", None))
        self.pushButton_view_all.setToolTip(_translate("DialogSite", "View alls records", None))
        self.pushButton_delete.setToolTip(_translate("DialogSite", "Delete record", None))
        self.pushButton_prev_rec.setToolTip(_translate("DialogSite", "Prev rec", None))
        self.pushButton_connect.setText(_translate("DialogSite", "Connection test", None))
        self.label_42.setText(_translate("DialogSite", "DB Info", None))
        self.label_43.setText(_translate("DialogSite", "Ordinamento", None))
        self.label_34.setText(_translate("DialogSite", "Status", None))
        self.label_27.setText(_translate("DialogSite", "record n.", None))
        self.label_rec_corrente.setText(_translate("DialogSite", "1", None))
        self.label_28.setText(_translate("DialogSite", "record tot.", None))
        self.label_rec_tot.setText(_translate("DialogSite", "1", None))
        self.comboBox_sito.setItemText(0, _translate("DialogSite", "Inserisci un valore", None))
        self.label.setText(_translate("DialogSite", "Sito", None))
        self.label_13.setText(_translate("DialogSite", "Dati descrittivi", None))
        self.label_6.setText(_translate("DialogSite", "Descrizione ", None))
        self.comboBox_nazione.setItemText(0, _translate("DialogSite", "Italia", None))
        self.label_4.setText(_translate("DialogSite", "Nazione", None))
        self.label_2.setText(_translate("DialogSite", "Comune", None))
        self.label_7.setText(_translate("DialogSite", "Provincia", None))
        self.label_5.setText(_translate("DialogSite", "Regione", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("DialogSite", "Dati descrittivi", None))
        self.label_8.setToolTip(_translate("DialogSite", "Carica tutti layer che contengono geometrie relative a questo sito", None))
        self.label_8.setText(_translate("DialogSite", "Carica i layer per questo sito", None))
        self.pushButton_sites_geometry.setText(_translate("DialogSite", "Carica", None))
        self.label_14.setText(_translate("DialogSite", "Genera un numero arbitrario di schede US per il sito corrente", None))
        self.pushButton_genera_us.setText(_translate("DialogSite", "Genera US (Azione irreversibile)", None))
        self.label_16.setText(_translate("DialogSite", "Numero Area", None))
        self.label_15.setText(_translate("DialogSite", "Numero di schede da creare", None))
        self.label_3.setToolTip(_translate("DialogSite", "Carica tutti i layer per poter inserire nuove geometrie", None))
        self.label_3.setText(_translate("DialogSite", "Carica layer per il disegno", None))
        self.pushButton_draw.setText(_translate("DialogSite", "Carica", None))
        self.label_9.setText(_translate("DialogSite", "Esporta relazione di scavo per questo sito (Versione di sviluppo)", None))
        self.pushButton_rel_pdf.setText(_translate("DialogSite", "Esporta", None))
        self.label_10.setText(_translate("DialogSite", "GIS Tools", None))
        self.label_12.setToolTip(_translate("DialogSite", "Carica tutti i layer per poter inserire nuove geometrie", None))
        self.label_12.setText(_translate("DialogSite", "Gis viewer", None))
        self.toolButton_draw_siti.setText(_translate("DialogSite", "Abilita il caricamento delle ricerche", None))
        self.label_11.setToolTip(_translate("DialogSite", "Carica tutti i layer per poter inserire nuove geometrie", None))
        self.label_11.setText(_translate("DialogSite", "Carica il puntuale del sito", None))
        self.pushButton_draw_sito.setText(_translate("DialogSite", "Carica", None))
        self.label_17.setText(_translate("DialogSite", "Numero di scheda US da cui partire", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("DialogSite", "Tools", None))
        self.pushButton_test.setText(_translate("DialogSite", "Run test", None))
        self.plainTextEdit.setPlainText(_translate("DialogSite", "Questa è una sezione di testing per sperimentare funzioni.\n"
"\n"
"\n"
"Procedura\n"
"Step 1 - Aprire il file test_area.py dentro alla cartella pyarchinit (la cartella si trova dentro al vostro utente /.qgis/python/plugins/pyarchinit)\n"
"\n"
"Step 2 - editare la funzione def run_test e salvare il file.\n"
"\n"
"Step 3 - Riavviare Qgis e cliccare sul pulsante Run Test per verificare l\'output della vostra funzione.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage3), _translate("DialogSite", "Python test area", None))

import resources_rc
