# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyarchinit_schedaind_ui.ui'
#
# Created: Thu Aug 21 16:38:23 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s


class Ui_DialogInd(object):
    def setupUi(self, DialogInd):
        DialogInd.setObjectName(_fromUtf8("DialogInd"))
        DialogInd.resize(609, 553)
        DialogInd.setMinimumSize(QtCore.QSize(540, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/iconPAI.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogInd.setWindowIcon(icon)
        self.gridLayout_6 = QtGui.QGridLayout(DialogInd)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_29 = QtGui.QLabel(DialogInd)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 0, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_42 = QtGui.QLabel(DialogInd)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_42.setFont(font)
        self.label_42.setAutoFillBackground(True)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_5.addWidget(self.label_42, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_43 = QtGui.QLabel(DialogInd)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_43.setFont(font)
        self.label_43.setMargin(0)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_4.addWidget(self.label_43, 0, 1, 1, 1)
        self.label_status = QtGui.QLabel(DialogInd)
        self.label_status.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_status.setFont(font)
        self.label_status.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_status.setMouseTracking(False)
        self.label_status.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_status.setFrameShape(QtGui.QFrame.Box)
        self.label_status.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_status.setText(_fromUtf8(""))
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setMargin(0)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.gridLayout_4.addWidget(self.label_status, 1, 0, 1, 1)
        self.label_sort = QtGui.QLabel(DialogInd)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_sort.setFont(font)
        self.label_sort.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_sort.setMouseTracking(False)
        self.label_sort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_sort.setFrameShape(QtGui.QFrame.Box)
        self.label_sort.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sort.setText(_fromUtf8(""))
        self.label_sort.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sort.setMargin(0)
        self.label_sort.setObjectName(_fromUtf8("label_sort"))
        self.gridLayout_4.addWidget(self.label_sort, 1, 1, 1, 1)
        self.label_34 = QtGui.QLabel(DialogInd)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_34.setFont(font)
        self.label_34.setMargin(0)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_4.addWidget(self.label_34, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_27 = QtGui.QLabel(DialogInd)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_27.setFont(font)
        self.label_27.setMargin(0)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_3.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_rec_corrente = QtGui.QLabel(DialogInd)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft Sans Serif"))
        font.setPointSize(12)
        self.label_rec_corrente.setFont(font)
        self.label_rec_corrente.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_corrente.setMouseTracking(False)
        self.label_rec_corrente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_corrente.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_corrente.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_corrente.setObjectName(_fromUtf8("label_rec_corrente"))
        self.gridLayout_3.addWidget(self.label_rec_corrente, 0, 1, 1, 1)
        self.label_28 = QtGui.QLabel(DialogInd)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setMargin(0)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_3.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_rec_tot = QtGui.QLabel(DialogInd)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft Sans Serif"))
        font.setPointSize(12)
        self.label_rec_tot.setFont(font)
        self.label_rec_tot.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_tot.setMouseTracking(False)
        self.label_rec_tot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_tot.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_tot.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_tot.setObjectName(_fromUtf8("label_rec_tot"))
        self.gridLayout_3.addWidget(self.label_rec_tot, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 0, 1, 3, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_last_rec = QtGui.QPushButton(DialogInd)
        self.pushButton_last_rec.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/7_rightArrows.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last_rec.setIcon(icon1)
        self.pushButton_last_rec.setObjectName(_fromUtf8("pushButton_last_rec"))
        self.gridLayout.addWidget(self.pushButton_last_rec, 0, 5, 1, 1)
        self.pushButton_new_rec = QtGui.QPushButton(DialogInd)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_rec.setFont(font)
        self.pushButton_new_rec.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/newrec.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_rec.setIcon(icon2)
        self.pushButton_new_rec.setObjectName(_fromUtf8("pushButton_new_rec"))
        self.gridLayout.addWidget(self.pushButton_new_rec, 0, 6, 1, 1)
        self.pushButton_save = QtGui.QPushButton(DialogInd)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/b_save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon3)
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.gridLayout.addWidget(self.pushButton_save, 0, 7, 1, 1)
        self.pushButton_new_search = QtGui.QPushButton(DialogInd)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_search.setFont(font)
        self.pushButton_new_search.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/new_search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_search.setIcon(icon4)
        self.pushButton_new_search.setObjectName(_fromUtf8("pushButton_new_search"))
        self.gridLayout.addWidget(self.pushButton_new_search, 1, 4, 1, 1)
        self.pushButton_search_go = QtGui.QPushButton(DialogInd)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_search_go.setFont(font)
        self.pushButton_search_go.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search_go.setIcon(icon5)
        self.pushButton_search_go.setObjectName(_fromUtf8("pushButton_search_go"))
        self.gridLayout.addWidget(self.pushButton_search_go, 1, 5, 1, 1)
        self.pushButton_sort = QtGui.QPushButton(DialogInd)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_sort.setFont(font)
        self.pushButton_sort.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/sort.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sort.setIcon(icon6)
        self.pushButton_sort.setObjectName(_fromUtf8("pushButton_sort"))
        self.gridLayout.addWidget(self.pushButton_sort, 1, 6, 1, 1)
        self.pushButton_view_all = QtGui.QPushButton(DialogInd)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_view_all.setFont(font)
        self.pushButton_view_all.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/view_all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_view_all.setIcon(icon7)
        self.pushButton_view_all.setObjectName(_fromUtf8("pushButton_view_all"))
        self.gridLayout.addWidget(self.pushButton_view_all, 1, 7, 1, 1)
        self.pushButton_next_rec = QtGui.QPushButton(DialogInd)
        self.pushButton_next_rec.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/6_rightArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_rec.setIcon(icon8)
        self.pushButton_next_rec.setObjectName(_fromUtf8("pushButton_next_rec"))
        self.gridLayout.addWidget(self.pushButton_next_rec, 0, 4, 1, 1)
        self.pushButton_prev_rec = QtGui.QPushButton(DialogInd)
        self.pushButton_prev_rec.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButton_prev_rec.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/4_leftArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prev_rec.setIcon(icon9)
        self.pushButton_prev_rec.setObjectName(_fromUtf8("pushButton_prev_rec"))
        self.gridLayout.addWidget(self.pushButton_prev_rec, 0, 3, 1, 1)
        self.pushButton_first_rec = QtGui.QPushButton(DialogInd)
        self.pushButton_first_rec.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/5_leftArrows.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_first_rec.setIcon(icon10)
        self.pushButton_first_rec.setObjectName(_fromUtf8("pushButton_first_rec"))
        self.gridLayout.addWidget(self.pushButton_first_rec, 0, 2, 1, 1)
        self.pushButton_delete = QtGui.QPushButton(DialogInd)
        self.pushButton_delete.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon11)
        self.pushButton_delete.setObjectName(_fromUtf8("pushButton_delete"))
        self.gridLayout.addWidget(self.pushButton_delete, 1, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.pushButton_connect = QtGui.QPushButton(DialogInd)
        self.pushButton_connect.setObjectName(_fromUtf8("pushButton_connect"))
        self.gridLayout_2.addWidget(self.pushButton_connect, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 0, 0, 1, 5)
        self.line_8 = QtGui.QFrame(DialogInd)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_6.addWidget(self.line_8, 1, 0, 1, 5)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.comboBox_sito = QtGui.QComboBox(DialogInd)
        self.comboBox_sito.setEnabled(False)
        self.comboBox_sito.setMinimumSize(QtCore.QSize(341, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_sito.setFont(font)
        self.comboBox_sito.setMouseTracking(True)
        self.comboBox_sito.setEditable(True)
        self.comboBox_sito.setMaxVisibleItems(99999)
        self.comboBox_sito.setMaxCount(2147483647)
        self.comboBox_sito.setObjectName(_fromUtf8("comboBox_sito"))
        self.comboBox_sito.addItem(_fromUtf8(""))
        self.verticalLayout_7.addWidget(self.comboBox_sito)
        self.label = QtGui.QLabel(DialogInd)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_7.addWidget(self.label)
        self.lineEdit_individuo = QtGui.QLineEdit(DialogInd)
        self.lineEdit_individuo.setEnabled(False)
        self.lineEdit_individuo.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_individuo.setObjectName(_fromUtf8("lineEdit_individuo"))
        self.verticalLayout_7.addWidget(self.lineEdit_individuo)
        self.label_19 = QtGui.QLabel(DialogInd)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_7.addWidget(self.label_19)
        self.gridLayout_6.addLayout(self.verticalLayout_7, 3, 1, 1, 3)
        spacerItem = QtGui.QSpacerItem(1000, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 4, 1, 1, 3)
        self.tabWidget = QtGui.QTabWidget(DialogInd)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setCursor(QtCore.Qt.ArrowCursor)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_21 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setText(_fromUtf8(""))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_7.addWidget(self.label_21, 1, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_20 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_4.addWidget(self.label_20)
        self.comboBox_sesso = QtGui.QComboBox(self.tab_7)
        self.comboBox_sesso.setEditable(True)
        self.comboBox_sesso.setObjectName(_fromUtf8("comboBox_sesso"))
        self.comboBox_sesso.addItem(_fromUtf8(""))
        self.comboBox_sesso.addItem(_fromUtf8(""))
        self.comboBox_sesso.addItem(_fromUtf8(""))
        self.comboBox_sesso.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.comboBox_sesso)
        self.gridLayout_7.addLayout(self.verticalLayout_4, 2, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_22 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_3.addWidget(self.label_22)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.comboBox_eta_min = QtGui.QComboBox(self.tab_7)
        self.comboBox_eta_min.setEditable(True)
        self.comboBox_eta_min.setObjectName(_fromUtf8("comboBox_eta_min"))
        self.comboBox_eta_min.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox_eta_min)
        self.label_24 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout.addWidget(self.label_24)
        self.comboBox_eta_max = QtGui.QComboBox(self.tab_7)
        self.comboBox_eta_max.setEnabled(True)
        self.comboBox_eta_max.setEditable(True)
        self.comboBox_eta_max.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.comboBox_eta_max.setObjectName(_fromUtf8("comboBox_eta_max"))
        self.comboBox_eta_max.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox_eta_max)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout_7.addLayout(self.verticalLayout_3, 2, 1, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_26 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_2.addWidget(self.label_26)
        self.comboBox_classi_eta = QtGui.QComboBox(self.tab_7)
        self.comboBox_classi_eta.setEditable(True)
        self.comboBox_classi_eta.setObjectName(_fromUtf8("comboBox_classi_eta"))
        self.comboBox_classi_eta.addItem(_fromUtf8(""))
        self.comboBox_classi_eta.setItemText(0, _fromUtf8(""))
        self.comboBox_classi_eta.addItem(_fromUtf8(""))
        self.comboBox_classi_eta.addItem(_fromUtf8(""))
        self.comboBox_classi_eta.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBox_classi_eta)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.textEdit_osservazioni = QtGui.QTextEdit(self.tab_7)
        self.textEdit_osservazioni.setObjectName(_fromUtf8("textEdit_osservazioni"))
        self.verticalLayout_5.addWidget(self.textEdit_osservazioni)
        self.label_23 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_5.addWidget(self.label_23)
        self.gridLayout_7.addLayout(self.verticalLayout_5, 3, 0, 1, 2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lineEdit_data_schedatura = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_data_schedatura.setObjectName(_fromUtf8("lineEdit_data_schedatura"))
        self.verticalLayout.addWidget(self.lineEdit_data_schedatura)
        self.label_15 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout.addWidget(self.label_15)
        self.gridLayout_7.addLayout(self.verticalLayout, 4, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lineEdit_schedatore = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_schedatore.setObjectName(_fromUtf8("lineEdit_schedatore"))
        self.verticalLayout_2.addWidget(self.lineEdit_schedatore)
        self.label_16 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_2.addWidget(self.label_16)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_12)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_68 = QtGui.QLabel(self.tab_12)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.verticalLayout_6.addWidget(self.label_68)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_71 = QtGui.QLabel(self.tab_12)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_71.setFont(font)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.horizontalLayout_13.addWidget(self.label_71)
        self.toolButtonGis = QtGui.QToolButton(self.tab_12)
        self.toolButtonGis.setMinimumSize(QtCore.QSize(109, 0))
        self.toolButtonGis.setToolTip(_fromUtf8(""))
        self.toolButtonGis.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/GIS.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonGis.setIcon(icon12)
        self.toolButtonGis.setCheckable(True)
        self.toolButtonGis.setChecked(False)
        self.toolButtonGis.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonGis.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonGis.setObjectName(_fromUtf8("toolButtonGis"))
        self.horizontalLayout_13.addWidget(self.toolButtonGis)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_72 = QtGui.QLabel(self.tab_12)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_72.setFont(font)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.horizontalLayout_14.addWidget(self.label_72)
        self.toolButtonPreview = QtGui.QToolButton(self.tab_12)
        self.toolButtonPreview.setEnabled(False)
        self.toolButtonPreview.setToolTip(_fromUtf8(""))
        self.toolButtonPreview.setIcon(icon12)
        self.toolButtonPreview.setCheckable(True)
        self.toolButtonPreview.setChecked(False)
        self.toolButtonPreview.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonPreview.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonPreview.setObjectName(_fromUtf8("toolButtonPreview"))
        self.horizontalLayout_14.addWidget(self.toolButtonPreview)
        self.toolButtonPan = QtGui.QToolButton(self.tab_12)
        self.toolButtonPan.setEnabled(False)
        self.toolButtonPan.setMinimumSize(QtCore.QSize(109, 0))
        self.toolButtonPan.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/mActionPan.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPan.setIcon(icon13)
        self.toolButtonPan.setCheckable(True)
        self.toolButtonPan.setChecked(False)
        self.toolButtonPan.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButtonPan.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonPan.setObjectName(_fromUtf8("toolButtonPan"))
        self.horizontalLayout_14.addWidget(self.toolButtonPan)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_74 = QtGui.QLabel(self.tab_12)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_74.setFont(font)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.horizontalLayout_16.addWidget(self.label_74)
        self.pushButton_pdf_exp = QtGui.QPushButton(self.tab_12)
        self.pushButton_pdf_exp.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_pdf_exp.setFont(font)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/sheet.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_pdf_exp.setIcon(icon14)
        self.pushButton_pdf_exp.setObjectName(_fromUtf8("pushButton_pdf_exp"))
        self.horizontalLayout_16.addWidget(self.pushButton_pdf_exp)
        self.pushButton_exp_index_ind = QtGui.QPushButton(self.tab_12)
        self.pushButton_exp_index_ind.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_exp_index_ind.setFont(font)
        self.pushButton_exp_index_ind.setIcon(icon14)
        self.pushButton_exp_index_ind.setObjectName(_fromUtf8("pushButton_exp_index_ind"))
        self.horizontalLayout_16.addWidget(self.pushButton_exp_index_ind)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_75 = QtGui.QLabel(self.tab_12)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_75.setFont(font)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.horizontalLayout_17.addWidget(self.label_75)
        self.toolButtonPreviewMedia = QtGui.QToolButton(self.tab_12)
        self.toolButtonPreviewMedia.setEnabled(False)
        self.toolButtonPreviewMedia.setMinimumSize(QtCore.QSize(109, 0))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/photo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPreviewMedia.setIcon(icon15)
        self.toolButtonPreviewMedia.setCheckable(True)
        self.toolButtonPreviewMedia.setObjectName(_fromUtf8("toolButtonPreviewMedia"))
        self.horizontalLayout_17.addWidget(self.toolButtonPreviewMedia)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.gridLayout_8.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem7, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_12, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.tabWidget, 5, 0, 1, 5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.lineEdit_area = QtGui.QLineEdit(DialogInd)
        self.lineEdit_area.setEnabled(False)
        self.lineEdit_area.setMinimumSize(QtCore.QSize(61, 25))
        self.lineEdit_area.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.lineEdit_area.setFont(font)
        self.lineEdit_area.setObjectName(_fromUtf8("lineEdit_area"))
        self.verticalLayout_10.addWidget(self.lineEdit_area)
        self.label_2 = QtGui.QLabel(DialogInd)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_10.addWidget(self.label_2)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.lineEdit_us = QtGui.QLineEdit(DialogInd)
        self.lineEdit_us.setEnabled(False)
        self.lineEdit_us.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_us.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_us.setObjectName(_fromUtf8("lineEdit_us"))
        self.verticalLayout_9.addWidget(self.lineEdit_us)
        self.label_3 = QtGui.QLabel(DialogInd)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_9.addWidget(self.label_3)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem9)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 3, 4, 1, 1)

        self.retranslateUi(DialogInd)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogInd)

    def retranslateUi(self, DialogInd):
        DialogInd.setWindowTitle(
            QtGui.QApplication.translate("DialogInd", "pyArchInit Gestione Scavi - Scheda Individuo", None,
                                         QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(
            QtGui.QApplication.translate("DialogInd", "DBMS Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(
            QtGui.QApplication.translate("DialogInd", "DB Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(
            QtGui.QApplication.translate("DialogInd", "Ordinamento", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("DialogInd", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(
            QtGui.QApplication.translate("DialogInd", "record n.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_corrente.setText(
            QtGui.QApplication.translate("DialogInd", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(
            QtGui.QApplication.translate("DialogInd", "record tot.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_tot.setText(QtGui.QApplication.translate("DialogInd", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_last_rec.setToolTip(
            QtGui.QApplication.translate("DialogInd", "Last rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_rec.setToolTip(
            QtGui.QApplication.translate("DialogInd", "New record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save.setToolTip(
            QtGui.QApplication.translate("DialogInd", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_search.setToolTip(
            QtGui.QApplication.translate("DialogInd", "new search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_search_go.setToolTip(
            QtGui.QApplication.translate("DialogInd", "search !!!", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_sort.setToolTip(
            QtGui.QApplication.translate("DialogInd", "Order by", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_view_all.setToolTip(
            QtGui.QApplication.translate("DialogInd", "View alls records", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_next_rec.setToolTip(
            QtGui.QApplication.translate("DialogInd", "Next rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_prev_rec.setToolTip(
            QtGui.QApplication.translate("DialogInd", "Prev rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_first_rec.setToolTip(
            QtGui.QApplication.translate("DialogInd", "First rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_delete.setToolTip(
            QtGui.QApplication.translate("DialogInd", "Delete record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_connect.setText(
            QtGui.QApplication.translate("DialogInd", "Connection test", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sito.setItemText(0, QtGui.QApplication.translate("DialogInd", "Inserisci un valore", None,
                                                                       QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogInd", "Sito ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(
            QtGui.QApplication.translate("DialogInd", "N. INDIVIDUO", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setToolTip(
            QtGui.QApplication.translate("DialogInd", "Grado/importanza", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(
            QtGui.QApplication.translate("DialogInd", "STIMA DEL SESSO", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sesso.setItemText(0, QtGui.QApplication.translate("DialogInd", "Non identificabile", None,
                                                                        QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sesso.setItemText(1, QtGui.QApplication.translate("DialogInd", "Maschio", None,
                                                                        QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sesso.setItemText(2, QtGui.QApplication.translate("DialogInd", "Femmina", None,
                                                                        QtGui.QApplication.UnicodeUTF8))
        self.comboBox_sesso.setItemText(3, QtGui.QApplication.translate("DialogInd", "Indeterminato", None,
                                                                        QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("DialogInd", "STIMA DELL\'ETA\' DI MORTE (in anni)", None,
                                                           QtGui.QApplication.UnicodeUTF8))
        self.comboBox_eta_min.setItemText(0, QtGui.QApplication.translate("DialogInd", "0", None,
                                                                          QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("DialogInd", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_eta_max.setItemText(0, QtGui.QApplication.translate("DialogInd", "0", None,
                                                                          QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(
            QtGui.QApplication.translate("DialogInd", "CLASSI DI ETA\'", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_classi_eta.setItemText(1,
                                             QtGui.QApplication.translate("DialogInd", "Adulto giovane (20-29)", None,
                                                                          QtGui.QApplication.UnicodeUTF8))
        self.comboBox_classi_eta.setItemText(2, QtGui.QApplication.translate("DialogInd", "Adulto maturo (30-50)", None,
                                                                             QtGui.QApplication.UnicodeUTF8))
        self.comboBox_classi_eta.setItemText(3,
                                             QtGui.QApplication.translate("DialogInd", "Adulto di eta\' avanzata (>50)",
                                                                          None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(
            QtGui.QApplication.translate("DialogInd", "OSSERVAZIONI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("DialogInd", "DATA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(
            QtGui.QApplication.translate("DialogInd", "SCHEDATORE", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7),
                                  QtGui.QApplication.translate("DialogInd", "Dati descrittivi", None,
                                                               QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(
            QtGui.QApplication.translate("DialogInd", "Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(
            QtGui.QApplication.translate("DialogInd", "Visualizzazione GIS", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonGis.setShortcut(
            QtGui.QApplication.translate("DialogInd", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.label_72.setText(QtGui.QApplication.translate("DialogInd", "Attivazione Preview pianta US", None,
                                                           QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPreview.setText(
            QtGui.QApplication.translate("DialogInd", "Preview pianta US", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPreview.setShortcut(
            QtGui.QApplication.translate("DialogInd", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPan.setToolTip(
            QtGui.QApplication.translate("DialogInd", "Pan tool", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPan.setShortcut(
            QtGui.QApplication.translate("DialogInd", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.label_74.setText(
            QtGui.QApplication.translate("DialogInd", "Esportain formato PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pdf_exp.setToolTip(
            QtGui.QApplication.translate("DialogInd", "Export PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pdf_exp.setText(
            QtGui.QApplication.translate("DialogInd", "Singole schede", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_exp_index_ind.setText(
            QtGui.QApplication.translate("DialogInd", "Elenco Individui", None, QtGui.QApplication.UnicodeUTF8))
        self.label_75.setText(
            QtGui.QApplication.translate("DialogInd", "Mostra immagini", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPreviewMedia.setText(
            QtGui.QApplication.translate("DialogInd", "Mostra immagini", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12),
                                  QtGui.QApplication.translate("DialogInd", "Tools", None,
                                                               QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogInd", "Area", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogInd", "US", None, QtGui.QApplication.UnicodeUTF8))
