# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyarchinit_pdf_administrator_ui.ui'
#
# Created: Tue Jan 29 16:38:50 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DialogPDFManager(object):
    def setupUi(self, DialogPDFManager):
        DialogPDFManager.setObjectName(_fromUtf8("DialogPDFManager"))
        DialogPDFManager.resize(624, 595)
        DialogPDFManager.setMinimumSize(QtCore.QSize(540, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/iconSite.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogPDFManager.setWindowIcon(icon)
        self.gridLayout_10 = QtGui.QGridLayout(DialogPDFManager)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_29 = QtGui.QLabel(DialogPDFManager)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 0, 0, 1, 1)
        self.pushButton_connect = QtGui.QPushButton(DialogPDFManager)
        self.pushButton_connect.setObjectName(_fromUtf8("pushButton_connect"))
        self.gridLayout_2.addWidget(self.pushButton_connect, 0, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_first_rec = QtGui.QPushButton(DialogPDFManager)
        self.pushButton_first_rec.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/5_leftArrows.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_first_rec.setIcon(icon1)
        self.pushButton_first_rec.setObjectName(_fromUtf8("pushButton_first_rec"))
        self.gridLayout.addWidget(self.pushButton_first_rec, 0, 0, 1, 1)
        self.pushButton_prev_rec = QtGui.QPushButton(DialogPDFManager)
        self.pushButton_prev_rec.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/4_leftArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prev_rec.setIcon(icon2)
        self.pushButton_prev_rec.setObjectName(_fromUtf8("pushButton_prev_rec"))
        self.gridLayout.addWidget(self.pushButton_prev_rec, 0, 1, 1, 2)
        self.pushButton_next_rec = QtGui.QPushButton(DialogPDFManager)
        self.pushButton_next_rec.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/6_rightArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_rec.setIcon(icon3)
        self.pushButton_next_rec.setObjectName(_fromUtf8("pushButton_next_rec"))
        self.gridLayout.addWidget(self.pushButton_next_rec, 0, 4, 1, 1)
        self.pushButton_last_rec = QtGui.QPushButton(DialogPDFManager)
        self.pushButton_last_rec.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/7_rightArrows.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last_rec.setIcon(icon4)
        self.pushButton_last_rec.setObjectName(_fromUtf8("pushButton_last_rec"))
        self.gridLayout.addWidget(self.pushButton_last_rec, 0, 5, 1, 1)
        self.pushButton_new_rec = QtGui.QPushButton(DialogPDFManager)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_rec.setFont(font)
        self.pushButton_new_rec.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/newrec.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_rec.setIcon(icon5)
        self.pushButton_new_rec.setObjectName(_fromUtf8("pushButton_new_rec"))
        self.gridLayout.addWidget(self.pushButton_new_rec, 0, 6, 1, 1)
        self.pushButton_save = QtGui.QPushButton(DialogPDFManager)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/b_save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon6)
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.gridLayout.addWidget(self.pushButton_save, 0, 7, 1, 1)
        self.pushButton_delete = QtGui.QPushButton(DialogPDFManager)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon7)
        self.pushButton_delete.setObjectName(_fromUtf8("pushButton_delete"))
        self.gridLayout.addWidget(self.pushButton_delete, 1, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(70, 30, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.pushButton_new_search = QtGui.QPushButton(DialogPDFManager)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_search.setFont(font)
        self.pushButton_new_search.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/new_search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_search.setIcon(icon8)
        self.pushButton_new_search.setObjectName(_fromUtf8("pushButton_new_search"))
        self.gridLayout.addWidget(self.pushButton_new_search, 1, 4, 1, 1)
        self.pushButton_search_go = QtGui.QPushButton(DialogPDFManager)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_search_go.setFont(font)
        self.pushButton_search_go.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search_go.setIcon(icon9)
        self.pushButton_search_go.setObjectName(_fromUtf8("pushButton_search_go"))
        self.gridLayout.addWidget(self.pushButton_search_go, 1, 5, 1, 1)
        self.pushButton_sort = QtGui.QPushButton(DialogPDFManager)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_sort.setFont(font)
        self.pushButton_sort.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/sort.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sort.setIcon(icon10)
        self.pushButton_sort.setObjectName(_fromUtf8("pushButton_sort"))
        self.gridLayout.addWidget(self.pushButton_sort, 1, 6, 1, 1)
        self.pushButton_view_all = QtGui.QPushButton(DialogPDFManager)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_view_all.setFont(font)
        self.pushButton_view_all.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/view_all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_view_all.setIcon(icon11)
        self.pushButton_view_all.setObjectName(_fromUtf8("pushButton_view_all"))
        self.gridLayout.addWidget(self.pushButton_view_all, 1, 7, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.line_6 = QtGui.QFrame(DialogPDFManager)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout.addWidget(self.line_6)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_42 = QtGui.QLabel(DialogPDFManager)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_42.setFont(font)
        self.label_42.setAutoFillBackground(True)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_5.addWidget(self.label_42, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_43 = QtGui.QLabel(DialogPDFManager)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_43.setFont(font)
        self.label_43.setMargin(0)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_4.addWidget(self.label_43, 0, 1, 1, 1)
        self.label_status = QtGui.QLabel(DialogPDFManager)
        self.label_status.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_status.setFont(font)
        self.label_status.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_status.setMouseTracking(False)
        self.label_status.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_status.setFrameShape(QtGui.QFrame.Box)
        self.label_status.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_status.setText(_fromUtf8(""))
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setMargin(0)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.gridLayout_4.addWidget(self.label_status, 1, 0, 1, 1)
        self.label_sort = QtGui.QLabel(DialogPDFManager)
        self.label_sort.setMinimumSize(QtCore.QSize(40, 0))
        self.label_sort.setSizeIncrement(QtCore.QSize(40, 0))
        self.label_sort.setBaseSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_sort.setFont(font)
        self.label_sort.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_sort.setMouseTracking(False)
        self.label_sort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_sort.setFrameShape(QtGui.QFrame.Box)
        self.label_sort.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sort.setText(_fromUtf8(""))
        self.label_sort.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sort.setMargin(0)
        self.label_sort.setObjectName(_fromUtf8("label_sort"))
        self.gridLayout_4.addWidget(self.label_sort, 1, 1, 1, 1)
        self.label_34 = QtGui.QLabel(DialogPDFManager)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_34.setFont(font)
        self.label_34.setMargin(0)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_4.addWidget(self.label_34, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_27 = QtGui.QLabel(DialogPDFManager)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_27.setFont(font)
        self.label_27.setMargin(0)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_3.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_rec_corrente = QtGui.QLabel(DialogPDFManager)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft Sans Serif"))
        font.setPointSize(12)
        self.label_rec_corrente.setFont(font)
        self.label_rec_corrente.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_corrente.setMouseTracking(False)
        self.label_rec_corrente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_corrente.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_corrente.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_corrente.setObjectName(_fromUtf8("label_rec_corrente"))
        self.gridLayout_3.addWidget(self.label_rec_corrente, 0, 1, 1, 1)
        self.label_28 = QtGui.QLabel(DialogPDFManager)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setMargin(0)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_3.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_rec_tot = QtGui.QLabel(DialogPDFManager)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft Sans Serif"))
        font.setPointSize(12)
        self.label_rec_tot.setFont(font)
        self.label_rec_tot.setCursor(QtCore.Qt.ForbiddenCursor)
        self.label_rec_tot.setMouseTracking(False)
        self.label_rec_tot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_tot.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_tot.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_tot.setObjectName(_fromUtf8("label_rec_tot"))
        self.gridLayout_3.addWidget(self.label_rec_tot, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_10.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(DialogPDFManager)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_tabella_corrente = QtGui.QLabel(DialogPDFManager)
        self.label_tabella_corrente.setMinimumSize(QtCore.QSize(200, 0))
        self.label_tabella_corrente.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_tabella_corrente.setFont(font)
        self.label_tabella_corrente.setText(_fromUtf8(""))
        self.label_tabella_corrente.setObjectName(_fromUtf8("label_tabella_corrente"))
        self.horizontalLayout_2.addWidget(self.label_tabella_corrente)
        spacerItem2 = QtGui.QSpacerItem(600, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_4 = QtGui.QLabel(DialogPDFManager)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.comboBox_modello = QtGui.QComboBox(DialogPDFManager)
        self.comboBox_modello.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_modello.setEditable(True)
        self.comboBox_modello.setObjectName(_fromUtf8("comboBox_modello"))
        self.horizontalLayout_2.addWidget(self.comboBox_modello)
        self.gridLayout_10.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(DialogPDFManager)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.comboBox_elenco_campi = QtGui.QComboBox(self.tab)
        self.comboBox_elenco_campi.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.comboBox_elenco_campi.setFont(font)
        self.comboBox_elenco_campi.setEditable(False)
        self.comboBox_elenco_campi.setObjectName(_fromUtf8("comboBox_elenco_campi"))
        self.gridLayout_9.addWidget(self.comboBox_elenco_campi, 8, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_9.addWidget(self.label_13, 4, 1, 1, 1)
        self.tableWidget_schema_griglia = QtGui.QTableWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_schema_griglia.sizePolicy().hasHeightForWidth())
        self.tableWidget_schema_griglia.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tableWidget_schema_griglia.setFont(font)
        self.tableWidget_schema_griglia.setFrameShape(QtGui.QFrame.WinPanel)
        self.tableWidget_schema_griglia.setFrameShadow(QtGui.QFrame.Sunken)
        self.tableWidget_schema_griglia.setLineWidth(1)
        self.tableWidget_schema_griglia.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_schema_griglia.setObjectName(_fromUtf8("tableWidget_schema_griglia"))
        self.tableWidget_schema_griglia.setColumnCount(9)
        self.tableWidget_schema_griglia.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_schema_griglia.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_schema_griglia.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_schema_griglia.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_schema_griglia.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_schema_griglia.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_schema_griglia.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_schema_griglia.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_schema_griglia.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_schema_griglia.setHorizontalHeaderItem(8, item)
        self.tableWidget_schema_griglia.horizontalHeader().setVisible(True)
        self.tableWidget_schema_griglia.horizontalHeader().setDefaultSectionSize(56)
        self.gridLayout_9.addWidget(self.tableWidget_schema_griglia, 6, 1, 1, 3)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_14 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_8.addWidget(self.label_14, 0, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_add_row_griglia = QtGui.QPushButton(self.tab)
        self.pushButton_add_row_griglia.setEnabled(True)
        self.pushButton_add_row_griglia.setObjectName(_fromUtf8("pushButton_add_row_griglia"))
        self.gridLayout_6.addWidget(self.pushButton_add_row_griglia, 0, 1, 1, 1)
        self.pushButton_remove_row_griglia = QtGui.QPushButton(self.tab)
        self.pushButton_remove_row_griglia.setEnabled(True)
        self.pushButton_remove_row_griglia.setObjectName(_fromUtf8("pushButton_remove_row_griglia"))
        self.gridLayout_6.addWidget(self.pushButton_remove_row_griglia, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_7.addWidget(self.label_2, 0, 0, 1, 1)
        self.pushButton_add_row_2 = QtGui.QPushButton(self.tab)
        self.pushButton_add_row_2.setEnabled(False)
        self.pushButton_add_row_2.setObjectName(_fromUtf8("pushButton_add_row_2"))
        self.gridLayout_7.addWidget(self.pushButton_add_row_2, 0, 1, 1, 1)
        self.pushButton_remove_row_2 = QtGui.QPushButton(self.tab)
        self.pushButton_remove_row_2.setEnabled(False)
        self.pushButton_remove_row_2.setObjectName(_fromUtf8("pushButton_remove_row_2"))
        self.gridLayout_7.addWidget(self.pushButton_remove_row_2, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 2, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 11, 3, 1, 1)
        self.pushButton_charge_default_schema = QtGui.QPushButton(self.tab)
        self.pushButton_charge_default_schema.setObjectName(_fromUtf8("pushButton_charge_default_schema"))
        self.gridLayout_9.addWidget(self.pushButton_charge_default_schema, 5, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_9.addWidget(self.label_9, 7, 1, 1, 1)
        self.pushButton_inserisci_nome_campo = QtGui.QPushButton(self.tab)
        self.pushButton_inserisci_nome_campo.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 127);"))
        self.pushButton_inserisci_nome_campo.setObjectName(_fromUtf8("pushButton_inserisci_nome_campo"))
        self.gridLayout_9.addWidget(self.pushButton_inserisci_nome_campo, 8, 2, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_16 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_14.addWidget(self.label_16, 0, 0, 1, 1)
        self.tableWidget_gestione_celle = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_gestione_celle.setFrameShape(QtGui.QFrame.WinPanel)
        self.tableWidget_gestione_celle.setFrameShadow(QtGui.QFrame.Sunken)
        self.tableWidget_gestione_celle.setLineWidth(1)
        self.tableWidget_gestione_celle.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_gestione_celle.setObjectName(_fromUtf8("tableWidget_gestione_celle"))
        self.tableWidget_gestione_celle.setColumnCount(4)
        self.tableWidget_gestione_celle.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_gestione_celle.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_gestione_celle.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_gestione_celle.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_gestione_celle.setHorizontalHeaderItem(3, item)
        self.gridLayout_14.addWidget(self.tableWidget_gestione_celle, 1, 0, 1, 2)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_15 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_11.addWidget(self.label_15, 0, 0, 1, 1)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_12.addWidget(self.label_3, 0, 0, 1, 1)
        self.pushButton_add_row_cell = QtGui.QPushButton(self.tab_2)
        self.pushButton_add_row_cell.setObjectName(_fromUtf8("pushButton_add_row_cell"))
        self.gridLayout_12.addWidget(self.pushButton_add_row_cell, 0, 1, 1, 1)
        self.pushButton_remove_row_cell = QtGui.QPushButton(self.tab_2)
        self.pushButton_remove_row_cell.setObjectName(_fromUtf8("pushButton_remove_row_cell"))
        self.gridLayout_12.addWidget(self.pushButton_remove_row_cell, 0, 2, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_12, 1, 0, 1, 1)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gridLayout_11.addLayout(self.gridLayout_13, 2, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_11, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_10.addWidget(self.tabWidget, 4, 0, 1, 1)

        self.retranslateUi(DialogPDFManager)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogPDFManager)

    def retranslateUi(self, DialogPDFManager):
        DialogPDFManager.setWindowTitle(QtGui.QApplication.translate("DialogPDFManager", "pyArchInit Gestione Scavi - Periodizzazione di scavo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("DialogPDFManager", "DBMS Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_connect.setText(QtGui.QApplication.translate("DialogPDFManager", "Reload DB", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_first_rec.setToolTip(QtGui.QApplication.translate("DialogPDFManager", "First rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_prev_rec.setToolTip(QtGui.QApplication.translate("DialogPDFManager", "Prev rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_next_rec.setToolTip(QtGui.QApplication.translate("DialogPDFManager", "Next rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_last_rec.setToolTip(QtGui.QApplication.translate("DialogPDFManager", "Last rec", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_rec.setToolTip(QtGui.QApplication.translate("DialogPDFManager", "New record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save.setToolTip(QtGui.QApplication.translate("DialogPDFManager", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_delete.setToolTip(QtGui.QApplication.translate("DialogPDFManager", "Delete record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_new_search.setToolTip(QtGui.QApplication.translate("DialogPDFManager", "new search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_search_go.setToolTip(QtGui.QApplication.translate("DialogPDFManager", "search !!!", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_sort.setToolTip(QtGui.QApplication.translate("DialogPDFManager", "Order by", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_view_all.setToolTip(QtGui.QApplication.translate("DialogPDFManager", "View alls records", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("DialogPDFManager", "DB Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("DialogPDFManager", "Ordinamento", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("DialogPDFManager", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("DialogPDFManager", "record n.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_corrente.setText(QtGui.QApplication.translate("DialogPDFManager", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("DialogPDFManager", "record tot.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_tot.setText(QtGui.QApplication.translate("DialogPDFManager", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DialogPDFManager", "Tabella corrente: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DialogPDFManager", "Modello", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("DialogPDFManager", "Schema griglia", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_schema_griglia.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogPDFManager", "Col 0", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_schema_griglia.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogPDFManager", "Col 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_schema_griglia.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("DialogPDFManager", "Col 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_schema_griglia.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("DialogPDFManager", "Col 3", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_schema_griglia.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("DialogPDFManager", "Col 4", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_schema_griglia.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("DialogPDFManager", "Col 5", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_schema_griglia.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("DialogPDFManager", "Col 6", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_schema_griglia.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("DialogPDFManager", "Col 7", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_schema_griglia.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("DialogPDFManager", "Col 8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("DialogPDFManager", "Gestione schema griglia", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogPDFManager", "Righe", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add_row_griglia.setText(QtGui.QApplication.translate("DialogPDFManager", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row_griglia.setText(QtGui.QApplication.translate("DialogPDFManager", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogPDFManager", "Colonne", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add_row_2.setText(QtGui.QApplication.translate("DialogPDFManager", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row_2.setText(QtGui.QApplication.translate("DialogPDFManager", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_charge_default_schema.setText(QtGui.QApplication.translate("DialogPDFManager", "Carica lo schema predefinito", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("DialogPDFManager", "Elenco Campi:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_inserisci_nome_campo.setText(QtGui.QApplication.translate("DialogPDFManager", "Inserisci nome del campo", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("DialogPDFManager", "Schema griglia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("DialogPDFManager", "Schema fusione celle", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_gestione_celle.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DialogPDFManager", "Comando", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_gestione_celle.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DialogPDFManager", "Cella iniziale", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_gestione_celle.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("DialogPDFManager", "Cella finale", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_gestione_celle.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("DialogPDFManager", "Riferimento", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("DialogPDFManager", "Gestione fusione celle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogPDFManager", "Righe", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add_row_cell.setText(QtGui.QApplication.translate("DialogPDFManager", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row_cell.setText(QtGui.QApplication.translate("DialogPDFManager", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("DialogPDFManager", "Fusione celle", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
