# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyarchinit_scheda_Lapidei_ui.ui'
#
# Created: Fri Jul 03 13:11:52 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_DialogSchedaLapidei(object):
    def setupUi(self, DialogSchedaLapidei):
        DialogSchedaLapidei.setObjectName(_fromUtf8("DialogSchedaLapidei"))
        DialogSchedaLapidei.resize(680, 599)
        DialogSchedaLapidei.setMinimumSize(QtCore.QSize(540, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/iconAlma.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogSchedaLapidei.setWindowIcon(icon)
        self.gridLayout_21 = QtGui.QGridLayout(DialogSchedaLapidei)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_32 = QtGui.QLabel(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_14.addWidget(self.label_32, 0, 0, 1, 1)
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.pushButton_first_rec = QtGui.QPushButton(DialogSchedaLapidei)
        self.pushButton_first_rec.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/5_leftArrows.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_first_rec.setIcon(icon1)
        self.pushButton_first_rec.setObjectName(_fromUtf8("pushButton_first_rec"))
        self.gridLayout_17.addWidget(self.pushButton_first_rec, 0, 5, 1, 1)
        self.pushButton_next_rec = QtGui.QPushButton(DialogSchedaLapidei)
        self.pushButton_next_rec.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/6_rightArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_rec.setIcon(icon2)
        self.pushButton_next_rec.setObjectName(_fromUtf8("pushButton_next_rec"))
        self.gridLayout_17.addWidget(self.pushButton_next_rec, 0, 7, 1, 1)
        self.pushButton_last_rec = QtGui.QPushButton(DialogSchedaLapidei)
        self.pushButton_last_rec.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/7_rightArrows.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last_rec.setIcon(icon3)
        self.pushButton_last_rec.setObjectName(_fromUtf8("pushButton_last_rec"))
        self.gridLayout_17.addWidget(self.pushButton_last_rec, 0, 8, 1, 1)
        self.pushButton_new_rec = QtGui.QPushButton(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_rec.setFont(font)
        self.pushButton_new_rec.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/newrec.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_rec.setIcon(icon4)
        self.pushButton_new_rec.setObjectName(_fromUtf8("pushButton_new_rec"))
        self.gridLayout_17.addWidget(self.pushButton_new_rec, 0, 9, 1, 1)
        self.pushButton_save = QtGui.QPushButton(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/b_save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon5)
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.gridLayout_17.addWidget(self.pushButton_save, 0, 10, 1, 1)
        self.pushButton_new_search = QtGui.QPushButton(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_new_search.setFont(font)
        self.pushButton_new_search.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/new_search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_new_search.setIcon(icon6)
        self.pushButton_new_search.setObjectName(_fromUtf8("pushButton_new_search"))
        self.gridLayout_17.addWidget(self.pushButton_new_search, 1, 7, 1, 1)
        self.pushButton_search_go = QtGui.QPushButton(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_search_go.setFont(font)
        self.pushButton_search_go.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search_go.setIcon(icon7)
        self.pushButton_search_go.setObjectName(_fromUtf8("pushButton_search_go"))
        self.gridLayout_17.addWidget(self.pushButton_search_go, 1, 8, 1, 1)
        self.pushButton_sort = QtGui.QPushButton(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_sort.setFont(font)
        self.pushButton_sort.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/sort.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sort.setIcon(icon8)
        self.pushButton_sort.setObjectName(_fromUtf8("pushButton_sort"))
        self.gridLayout_17.addWidget(self.pushButton_sort, 1, 9, 1, 1)
        self.pushButton_view_all_2 = QtGui.QPushButton(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_view_all_2.setFont(font)
        self.pushButton_view_all_2.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/view_all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_view_all_2.setIcon(icon9)
        self.pushButton_view_all_2.setObjectName(_fromUtf8("pushButton_view_all_2"))
        self.gridLayout_17.addWidget(self.pushButton_view_all_2, 1, 10, 1, 1)
        self.pushButton_delete = QtGui.QPushButton(DialogSchedaLapidei)
        self.pushButton_delete.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon10)
        self.pushButton_delete.setObjectName(_fromUtf8("pushButton_delete"))
        self.gridLayout_17.addWidget(self.pushButton_delete, 1, 2, 1, 1)
        self.pushButton_prev_rec = QtGui.QPushButton(DialogSchedaLapidei)
        self.pushButton_prev_rec.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/4_leftArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prev_rec.setIcon(icon11)
        self.pushButton_prev_rec.setObjectName(_fromUtf8("pushButton_prev_rec"))
        self.gridLayout_17.addWidget(self.pushButton_prev_rec, 0, 6, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_17, 2, 0, 1, 2)
        self.pushButton_connect = QtGui.QPushButton(DialogSchedaLapidei)
        self.pushButton_connect.setObjectName(_fromUtf8("pushButton_connect"))
        self.gridLayout_14.addWidget(self.pushButton_connect, 1, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_14)
        self.line_7 = QtGui.QFrame(DialogSchedaLapidei)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout_3.addWidget(self.line_7)
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.label_44 = QtGui.QLabel(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setAutoFillBackground(True)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_18.addWidget(self.label_44, 0, 0, 1, 1)
        self.gridLayout_19 = QtGui.QGridLayout()
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.label_45 = QtGui.QLabel(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setMargin(0)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_19.addWidget(self.label_45, 0, 1, 1, 1)
        self.label_status = QtGui.QLabel(DialogSchedaLapidei)
        self.label_status.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_status.setMouseTracking(False)
        self.label_status.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_status.setFrameShape(QtGui.QFrame.Box)
        self.label_status.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_status.setText(_fromUtf8(""))
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setMargin(0)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.gridLayout_19.addWidget(self.label_status, 1, 0, 1, 1)
        self.label_sort = QtGui.QLabel(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_sort.setFont(font)
        self.label_sort.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_sort.setMouseTracking(False)
        self.label_sort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_sort.setFrameShape(QtGui.QFrame.Box)
        self.label_sort.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sort.setText(_fromUtf8(""))
        self.label_sort.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sort.setMargin(0)
        self.label_sort.setObjectName(_fromUtf8("label_sort"))
        self.gridLayout_19.addWidget(self.label_sort, 1, 1, 1, 1)
        self.label_35 = QtGui.QLabel(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setMargin(0)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_19.addWidget(self.label_35, 0, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_19, 1, 0, 1, 1)
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.label_33 = QtGui.QLabel(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setMargin(0)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_20.addWidget(self.label_33, 0, 0, 1, 1)
        self.label_rec_corrente = QtGui.QLabel(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft Sans Serif"))
        font.setPointSize(12)
        self.label_rec_corrente.setFont(font)
        self.label_rec_corrente.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_rec_corrente.setMouseTracking(False)
        self.label_rec_corrente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_corrente.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_corrente.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_corrente.setObjectName(_fromUtf8("label_rec_corrente"))
        self.gridLayout_20.addWidget(self.label_rec_corrente, 0, 1, 1, 1)
        self.label_36 = QtGui.QLabel(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setMargin(0)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_20.addWidget(self.label_36, 1, 0, 1, 1)
        self.label_rec_tot = QtGui.QLabel(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft Sans Serif"))
        font.setPointSize(12)
        self.label_rec_tot.setFont(font)
        self.label_rec_tot.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_rec_tot.setMouseTracking(False)
        self.label_rec_tot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rec_tot.setFrameShape(QtGui.QFrame.Box)
        self.label_rec_tot.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_rec_tot.setObjectName(_fromUtf8("label_rec_tot"))
        self.gridLayout_20.addWidget(self.label_rec_tot, 1, 1, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_20, 2, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_18)
        self.gridLayout_21.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.line_8 = QtGui.QFrame(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_6.addWidget(self.line_8, 0, 0, 1, 3)
        self.label_5 = QtGui.QLabel(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 5, 1, 1, 1)
        self.lineEdit_num_inv = QtGui.QLineEdit(DialogSchedaLapidei)
        self.lineEdit_num_inv.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_num_inv.setFont(font)
        self.lineEdit_num_inv.setObjectName(_fromUtf8("lineEdit_num_inv"))
        self.gridLayout_6.addWidget(self.lineEdit_num_inv, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_6.addWidget(self.label_3, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(300, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 3, 1, 1, 1)
        self.label = QtGui.QLabel(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 3, 2, 1, 1)
        self.comboBox_materiale = QtGui.QComboBox(DialogSchedaLapidei)
        self.comboBox_materiale.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_materiale.setFont(font)
        self.comboBox_materiale.setMouseTracking(True)
        self.comboBox_materiale.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox_materiale.setEditable(True)
        self.comboBox_materiale.setMaxVisibleItems(99999)
        self.comboBox_materiale.setMaxCount(2147483647)
        self.comboBox_materiale.setFrame(False)
        self.comboBox_materiale.setObjectName(_fromUtf8("comboBox_materiale"))
        self.comboBox_materiale.addItem(_fromUtf8(""))
        self.comboBox_materiale.addItem(_fromUtf8(""))
        self.comboBox_materiale.addItem(_fromUtf8(""))
        self.comboBox_materiale.addItem(_fromUtf8(""))
        self.comboBox_materiale.addItem(_fromUtf8(""))
        self.comboBox_materiale.addItem(_fromUtf8(""))
        self.comboBox_materiale.addItem(_fromUtf8(""))
        self.comboBox_materiale.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBox_materiale, 4, 2, 1, 1)
        self.comboBox_tipologia = QtGui.QComboBox(DialogSchedaLapidei)
        self.comboBox_tipologia.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_tipologia.setFont(font)
        self.comboBox_tipologia.setMouseTracking(True)
        self.comboBox_tipologia.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox_tipologia.setEditable(True)
        self.comboBox_tipologia.setMaxVisibleItems(99999)
        self.comboBox_tipologia.setMaxCount(2147483647)
        self.comboBox_tipologia.setFrame(False)
        self.comboBox_tipologia.setObjectName(_fromUtf8("comboBox_tipologia"))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.comboBox_tipologia.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBox_tipologia, 4, 1, 1, 1)
        self.label_27 = QtGui.QLabel(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_6.addWidget(self.label_27, 9, 2, 1, 1)
        self.comboBox_oggetto = QtGui.QComboBox(DialogSchedaLapidei)
        self.comboBox_oggetto.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_oggetto.setFont(font)
        self.comboBox_oggetto.setMouseTracking(True)
        self.comboBox_oggetto.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox_oggetto.setEditable(True)
        self.comboBox_oggetto.setMaxVisibleItems(99999)
        self.comboBox_oggetto.setMaxCount(2147483647)
        self.comboBox_oggetto.setFrame(False)
        self.comboBox_oggetto.setObjectName(_fromUtf8("comboBox_oggetto"))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.comboBox_oggetto.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBox_oggetto, 8, 1, 1, 1)
        self.lineEdit_compilatore = QtGui.QLineEdit(DialogSchedaLapidei)
        self.lineEdit_compilatore.setObjectName(_fromUtf8("lineEdit_compilatore"))
        self.gridLayout_6.addWidget(self.lineEdit_compilatore, 4, 0, 1, 1)
        self.label_7 = QtGui.QLabel(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 5, 2, 1, 1)
        self.label_2 = QtGui.QLabel(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 5, 0, 1, 1)
        self.lineEdit_collocazione = QtGui.QLineEdit(DialogSchedaLapidei)
        self.lineEdit_collocazione.setObjectName(_fromUtf8("lineEdit_collocazione"))
        self.gridLayout_6.addWidget(self.lineEdit_collocazione, 8, 2, 1, 1)
        self.label_4 = QtGui.QLabel(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 9, 1, 1, 1)
        self.comboBox_sito = QtGui.QComboBox(DialogSchedaLapidei)
        self.comboBox_sito.setObjectName(_fromUtf8("comboBox_sito"))
        self.gridLayout_6.addWidget(self.comboBox_sito, 1, 0, 1, 2)
        self.gridLayout_21.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(DialogSchedaLapidei)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_16 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.line = QtGui.QFrame(self.tab_3)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_16.addWidget(self.line, 0, 1, 3, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 179, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem1, 1, 2, 2, 1)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.lineEdit_h = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_h.setObjectName(_fromUtf8("lineEdit_h"))
        self.gridLayout_11.addWidget(self.lineEdit_h, 5, 1, 1, 1)
        self.lineEdit_d_letto_posa = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_d_letto_posa.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_d_letto_posa.setText(_fromUtf8(""))
        self.lineEdit_d_letto_posa.setObjectName(_fromUtf8("lineEdit_d_letto_posa"))
        self.gridLayout_11.addWidget(self.lineEdit_d_letto_posa, 0, 1, 1, 1)
        self.lineEdit_spessore = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_spessore.setObjectName(_fromUtf8("lineEdit_spessore"))
        self.gridLayout_11.addWidget(self.lineEdit_spessore, 6, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_11.addWidget(self.label_25, 4, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.tab_3)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_11.addWidget(self.label_29, 1, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_11.addWidget(self.label_21, 2, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.tab_3)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_11.addWidget(self.label_28, 6, 2, 1, 1)
        self.lineEdit_d_letto_attesa = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_d_letto_attesa.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_d_letto_attesa.setObjectName(_fromUtf8("lineEdit_d_letto_attesa"))
        self.gridLayout_11.addWidget(self.lineEdit_d_letto_attesa, 1, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab_3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_11.addWidget(self.label_20, 6, 0, 1, 1)
        self.lineEdit_larghezza = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_larghezza.setObjectName(_fromUtf8("lineEdit_larghezza"))
        self.gridLayout_11.addWidget(self.lineEdit_larghezza, 2, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_11.addWidget(self.label_16, 3, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_11.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.tab_3)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_11.addWidget(self.label_26, 5, 2, 1, 1)
        self.lineEdit_lunghezza = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_lunghezza.setObjectName(_fromUtf8("lineEdit_lunghezza"))
        self.gridLayout_11.addWidget(self.lineEdit_lunghezza, 3, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.tab_3)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_11.addWidget(self.label_30, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_11.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_11.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_11.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_11.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_11.addWidget(self.label_24, 4, 0, 1, 1)
        self.lineEdit_toro = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_toro.setObjectName(_fromUtf8("lineEdit_toro"))
        self.gridLayout_11.addWidget(self.lineEdit_toro, 4, 1, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_11, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.textEdit_descrizione = QtGui.QTextEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_descrizione.setFont(font)
        self.textEdit_descrizione.setObjectName(_fromUtf8("textEdit_descrizione"))
        self.horizontalLayout_2.addWidget(self.textEdit_descrizione)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.textEdit_lavorazione_e_stato_di_conservazione = QtGui.QTextEdit(self.tab_4)
        self.textEdit_lavorazione_e_stato_di_conservazione.setObjectName(
            _fromUtf8("textEdit_lavorazione_e_stato_di_conservazione"))
        self.gridLayout.addWidget(self.textEdit_lavorazione_e_stato_di_conservazione, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.gridLayout.addLayout(self.formLayout_3, 0, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_32 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_32.setObjectName(_fromUtf8("gridLayout_32"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEdit_cronologia = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_cronologia.setObjectName(_fromUtf8("lineEdit_cronologia"))
        self.horizontalLayout.addWidget(self.lineEdit_cronologia)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.gridLayout_32.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.tab_8)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 638, 235))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.textEdit_confronti = QtGui.QTextEdit(self.gridLayoutWidget_4)
        self.textEdit_confronti.setObjectName(_fromUtf8("textEdit_confronti"))
        self.gridLayout_4.addWidget(self.textEdit_confronti, 0, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_4.addWidget(self.label_18, 0, 0, 1, 1)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.gridLayout_4.addLayout(self.formLayout_5, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_8, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_22 = QtGui.QLabel(self.tab_7)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_12.addWidget(self.label_22, 0, 0, 1, 1)
        self.pushButton_insert_row_bibliografia = QtGui.QPushButton(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_insert_row_bibliografia.setFont(font)
        self.pushButton_insert_row_bibliografia.setObjectName(_fromUtf8("pushButton_insert_row_bibliografia"))
        self.gridLayout_12.addWidget(self.pushButton_insert_row_bibliografia, 0, 1, 1, 1)
        self.pushButton_remove_row_bibliografia = QtGui.QPushButton(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_remove_row_bibliografia.setFont(font)
        self.pushButton_remove_row_bibliografia.setObjectName(_fromUtf8("pushButton_remove_row_bibliografia"))
        self.gridLayout_12.addWidget(self.pushButton_remove_row_bibliografia, 0, 2, 1, 1)
        self.tableWidget_bibliografia = QtGui.QTableWidget(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget_bibliografia.setFont(font)
        self.tableWidget_bibliografia.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget_bibliografia.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget_bibliografia.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_bibliografia.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_bibliografia.setEditTriggers(
            QtGui.QAbstractItemView.AnyKeyPressed | QtGui.QAbstractItemView.DoubleClicked | QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_bibliografia.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_bibliografia.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_bibliografia.setRowCount(1)
        self.tableWidget_bibliografia.setColumnCount(5)
        self.tableWidget_bibliografia.setObjectName(_fromUtf8("tableWidget_bibliografia"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget_bibliografia.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_bibliografia.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_bibliografia.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_bibliografia.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_bibliografia.setHorizontalHeaderItem(4, item)
        self.gridLayout_12.addWidget(self.tableWidget_bibliografia, 1, 0, 1, 3)
        self.gridLayout_15.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.formLayout = QtGui.QFormLayout(self.tab_5)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.pushButton_exp_pdf_sheet = QtGui.QPushButton(self.tab_5)
        self.pushButton_exp_pdf_sheet.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_exp_pdf_sheet.setObjectName(_fromUtf8("pushButton_exp_pdf_sheet"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.pushButton_exp_pdf_sheet)
        self.mdiArea = QtGui.QMdiArea(self.tab_5)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.mdiArea)
        self.pushButton_image = QtGui.QPushButton(self.tab_5)
        self.pushButton_image.setObjectName(_fromUtf8("pushButton_image"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.pushButton_image)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout_21.addWidget(self.tabWidget, 2, 0, 1, 1)

        self.retranslateUi(DialogSchedaLapidei)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogSchedaLapidei)
        DialogSchedaLapidei.setTabOrder(self.lineEdit_num_inv, self.comboBox_tipologia)
        DialogSchedaLapidei.setTabOrder(self.comboBox_tipologia, self.comboBox_materiale)
        DialogSchedaLapidei.setTabOrder(self.comboBox_materiale, self.comboBox_oggetto)
        DialogSchedaLapidei.setTabOrder(self.comboBox_oggetto, self.textEdit_descrizione)
        DialogSchedaLapidei.setTabOrder(self.textEdit_descrizione, self.lineEdit_d_letto_posa)
        DialogSchedaLapidei.setTabOrder(self.lineEdit_d_letto_posa, self.lineEdit_d_letto_attesa)
        DialogSchedaLapidei.setTabOrder(self.lineEdit_d_letto_attesa, self.lineEdit_lunghezza)
        DialogSchedaLapidei.setTabOrder(self.lineEdit_lunghezza, self.lineEdit_toro)
        DialogSchedaLapidei.setTabOrder(self.lineEdit_toro, self.tableWidget_bibliografia)
        DialogSchedaLapidei.setTabOrder(self.tableWidget_bibliografia, self.tabWidget)
        DialogSchedaLapidei.setTabOrder(self.tabWidget, self.pushButton_insert_row_bibliografia)
        DialogSchedaLapidei.setTabOrder(self.pushButton_insert_row_bibliografia,
                                        self.pushButton_remove_row_bibliografia)

    def retranslateUi(self, DialogSchedaLapidei):
        DialogSchedaLapidei.setWindowTitle(_translate("DialogSchedaLapidei", "Scheda reperti lapidei", None))
        self.label_32.setText(_translate("DialogSchedaLapidei", "DBMS Toolbar", None))
        self.pushButton_first_rec.setToolTip(_translate("DialogSchedaLapidei", "First rec", None))
        self.pushButton_next_rec.setToolTip(_translate("DialogSchedaLapidei", "Next rec", None))
        self.pushButton_last_rec.setToolTip(_translate("DialogSchedaLapidei", "Last rec", None))
        self.pushButton_new_rec.setToolTip(_translate("DialogSchedaLapidei", "New record", None))
        self.pushButton_save.setToolTip(_translate("DialogSchedaLapidei", "Save", None))
        self.pushButton_new_search.setToolTip(_translate("DialogSchedaLapidei", "new search", None))
        self.pushButton_search_go.setToolTip(_translate("DialogSchedaLapidei", "search !!!", None))
        self.pushButton_sort.setToolTip(_translate("DialogSchedaLapidei", "Order by", None))
        self.pushButton_view_all_2.setToolTip(_translate("DialogSchedaLapidei", "View alls records", None))
        self.pushButton_delete.setToolTip(_translate("DialogSchedaLapidei", "Delete record", None))
        self.pushButton_prev_rec.setToolTip(_translate("DialogSchedaLapidei", "Prev rec", None))
        self.pushButton_connect.setText(_translate("DialogSchedaLapidei", "Connection test", None))
        self.label_44.setText(_translate("DialogSchedaLapidei", "DB Info", None))
        self.label_45.setText(_translate("DialogSchedaLapidei", "Ordinamento", None))
        self.label_35.setText(_translate("DialogSchedaLapidei", "Status", None))
        self.label_33.setText(_translate("DialogSchedaLapidei", "record n.", None))
        self.label_rec_corrente.setText(_translate("DialogSchedaLapidei", "1", None))
        self.label_36.setText(_translate("DialogSchedaLapidei", "record tot.", None))
        self.label_rec_tot.setText(_translate("DialogSchedaLapidei", "1", None))
        self.label_5.setText(_translate("DialogSchedaLapidei", "Tipologia", None))
        self.lineEdit_num_inv.setText(_translate("DialogSchedaLapidei", "0", None))
        self.label_3.setText(_translate("DialogSchedaLapidei", "Contesto/Provenienza", None))
        self.label.setText(_translate("DialogSchedaLapidei", "Scheda N.", None))
        self.comboBox_materiale.setItemText(0, _translate("DialogSchedaLapidei", "Ceramica", None))
        self.comboBox_materiale.setItemText(1, _translate("DialogSchedaLapidei", "Elemento marmoreo", None))
        self.comboBox_materiale.setItemText(2, _translate("DialogSchedaLapidei", "Elemento lapideo", None))
        self.comboBox_materiale.setItemText(3, _translate("DialogSchedaLapidei", "Moneta", None))
        self.comboBox_materiale.setItemText(4, _translate("DialogSchedaLapidei", "Vetro", None))
        self.comboBox_materiale.setItemText(5, _translate("DialogSchedaLapidei", "Metallo", None))
        self.comboBox_materiale.setItemText(6, _translate("DialogSchedaLapidei", "Avorio", None))
        self.comboBox_materiale.setItemText(7, _translate("DialogSchedaLapidei", "Osso", None))
        self.comboBox_tipologia.setItemText(0, _translate("DialogSchedaLapidei", "Tipo attico", None))
        self.comboBox_tipologia.setItemText(1, _translate("DialogSchedaLapidei", "Tipo attico a doppio listello", None))
        self.comboBox_tipologia.setItemText(2, _translate("DialogSchedaLapidei", "A profilo semplificato", None))
        self.comboBox_tipologia.setItemText(3, _translate("DialogSchedaLapidei", "Binata", None))
        self.comboBox_tipologia.setItemText(4, _translate("DialogSchedaLapidei", "A dado", None))
        self.comboBox_tipologia.setItemText(5, _translate("DialogSchedaLapidei", "Poligonale", None))
        self.comboBox_tipologia.setItemText(6, _translate("DialogSchedaLapidei", "Liscio", None))
        self.comboBox_tipologia.setItemText(7, _translate("DialogSchedaLapidei", "Rudentato", None))
        self.comboBox_tipologia.setItemText(8, _translate("DialogSchedaLapidei", "Scanalato", None))
        self.comboBox_tipologia.setItemText(9, _translate("DialogSchedaLapidei", "Binato", None))
        self.comboBox_tipologia.setItemText(10, _translate("DialogSchedaLapidei", "Dorico", None))
        self.comboBox_tipologia.setItemText(11, _translate("DialogSchedaLapidei", "Ionico", None))
        self.comboBox_tipologia.setItemText(12, _translate("DialogSchedaLapidei", "Corinzio", None))
        self.comboBox_tipologia.setItemText(13, _translate("DialogSchedaLapidei", "Ionico ad imposta", None))
        self.comboBox_tipologia.setItemText(14, _translate("DialogSchedaLapidei", "Composito", None))
        self.comboBox_tipologia.setItemText(15, _translate("DialogSchedaLapidei", "A canestro", None))
        self.comboBox_tipologia.setItemText(16, _translate("DialogSchedaLapidei", "A cesto", None))
        self.comboBox_tipologia.setItemText(17, _translate("DialogSchedaLapidei", "Polilobato", None))
        self.comboBox_tipologia.setItemText(18, _translate("DialogSchedaLapidei", "Binata", None))
        self.comboBox_tipologia.setItemText(19, _translate("DialogSchedaLapidei", "A stampella", None))
        self.comboBox_tipologia.setItemText(20, _translate("DialogSchedaLapidei", "Pluteo", None))
        self.comboBox_tipologia.setItemText(21, _translate("DialogSchedaLapidei", "Transenna", None))
        self.comboBox_tipologia.setItemText(22, _translate("DialogSchedaLapidei", "Di iconostasi", None))
        self.comboBox_tipologia.setItemText(23, _translate("DialogSchedaLapidei", "Di ambone", None))
        self.comboBox_tipologia.setItemText(24, _translate("DialogSchedaLapidei", "Di mensa", None))
        self.label_27.setText(_translate("DialogSchedaLapidei", "Collocazione", None))
        self.comboBox_oggetto.setItemText(0, _translate("DialogSchedaLapidei", "Base di colonna", None))
        self.comboBox_oggetto.setItemText(1, _translate("DialogSchedaLapidei", "Basamento", None))
        self.comboBox_oggetto.setItemText(2, _translate("DialogSchedaLapidei", "Fusto di colonna", None))
        self.comboBox_oggetto.setItemText(3, _translate("DialogSchedaLapidei", "Capitello", None))
        self.comboBox_oggetto.setItemText(4, _translate("DialogSchedaLapidei", "Pulvino", None))
        self.comboBox_oggetto.setItemText(5, _translate("DialogSchedaLapidei", "Lastra", None))
        self.comboBox_oggetto.setItemText(6, _translate("DialogSchedaLapidei", "Stilobate", None))
        self.comboBox_oggetto.setItemText(7, _translate("DialogSchedaLapidei", "Cornice", None))
        self.comboBox_oggetto.setItemText(8, _translate("DialogSchedaLapidei", "Stipite", None))
        self.comboBox_oggetto.setItemText(9, _translate("DialogSchedaLapidei", "Arco", None))
        self.comboBox_oggetto.setItemText(10, _translate("DialogSchedaLapidei", "Architrave", None))
        self.comboBox_oggetto.setItemText(11, _translate("DialogSchedaLapidei", "New Item", None))
        self.comboBox_oggetto.setItemText(12, _translate("DialogSchedaLapidei", "Mensola", None))
        self.comboBox_oggetto.setItemText(13, _translate("DialogSchedaLapidei", "Balaustra", None))
        self.comboBox_oggetto.setItemText(14, _translate("DialogSchedaLapidei", "Cimasa", None))
        self.comboBox_oggetto.setItemText(15, _translate("DialogSchedaLapidei", "Parapetto di ambone", None))
        self.comboBox_oggetto.setItemText(16, _translate("DialogSchedaLapidei", "Piattaforma di ambone", None))
        self.comboBox_oggetto.setItemText(17, _translate("DialogSchedaLapidei", "Solea", None))
        self.comboBox_oggetto.setItemText(18, _translate("DialogSchedaLapidei", "Pilastrino", None))
        self.comboBox_oggetto.setItemText(19, _translate("DialogSchedaLapidei", "Colonnina", None))
        self.comboBox_oggetto.setItemText(20, _translate("DialogSchedaLapidei", "Trapeza", None))
        self.label_7.setText(_translate("DialogSchedaLapidei", "Materiale", None))
        self.label_2.setText(_translate("DialogSchedaLapidei", "Autore scheda", None))
        self.label_4.setText(_translate("DialogSchedaLapidei", "Oggetto", None))
        self.label_25.setText(_translate("DialogSchedaLapidei", "m", None))
        self.label_29.setText(_translate("DialogSchedaLapidei", "m", None))
        self.label_21.setText(_translate("DialogSchedaLapidei", "m", None))
        self.label_28.setText(_translate("DialogSchedaLapidei", "m", None))
        self.label_20.setText(_translate("DialogSchedaLapidei", "Spessore", None))
        self.label_16.setText(_translate("DialogSchedaLapidei", "m", None))
        self.label_10.setText(_translate("DialogSchedaLapidei", "Larghezza", None))
        self.label_26.setText(_translate("DialogSchedaLapidei", "m", None))
        self.label_30.setText(_translate("DialogSchedaLapidei", "m", None))
        self.label_8.setText(_translate("DialogSchedaLapidei", "D(letto posa)", None))
        self.label_14.setText(_translate("DialogSchedaLapidei", "Lunghezza", None))
        self.label_9.setText(_translate("DialogSchedaLapidei", "d(letto attesa)", None))
        self.label_13.setText(_translate("DialogSchedaLapidei", "h", None))
        self.label_24.setText(_translate("DialogSchedaLapidei", "Toro", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3),
                                  _translate("DialogSchedaLapidei", "Dimensioni", None))
        self.label_6.setText(_translate("DialogSchedaLapidei", "Descrizione ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab),
                                  _translate("DialogSchedaLapidei", "Descrizione", None))
        self.label_11.setText(_translate("DialogSchedaLapidei", "Lavorazione", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4),
                                  _translate("DialogSchedaLapidei", "Lavorazione e stato di conservazione", None))
        self.label_12.setText(_translate("DialogSchedaLapidei", "Cronologia", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2),
                                  _translate("DialogSchedaLapidei", "Cronologia", None))
        self.label_18.setText(_translate("DialogSchedaLapidei", "Confronti", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8),
                                  _translate("DialogSchedaLapidei", "Confronti", None))
        self.label_22.setText(_translate("DialogSchedaLapidei", "Bibliografia", None))
        self.pushButton_insert_row_bibliografia.setText(_translate("DialogSchedaLapidei", "inserisci riga", None))
        self.pushButton_remove_row_bibliografia.setText(_translate("DialogSchedaLapidei", "rimuovi riga", None))
        item = self.tableWidget_bibliografia.horizontalHeaderItem(0)
        item.setText(_translate("DialogSchedaLapidei", "Autore", None))
        item = self.tableWidget_bibliografia.horizontalHeaderItem(1)
        item.setText(_translate("DialogSchedaLapidei", "Anno", None))
        item = self.tableWidget_bibliografia.horizontalHeaderItem(2)
        item.setText(_translate("DialogSchedaLapidei", "Titolo", None))
        item = self.tableWidget_bibliografia.horizontalHeaderItem(3)
        item.setText(_translate("DialogSchedaLapidei", "Pag.", None))
        item = self.tableWidget_bibliografia.horizontalHeaderItem(4)
        item.setText(_translate("DialogSchedaLapidei", "Fig.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7),
                                  _translate("DialogSchedaLapidei", "Bibliografia", None))
        self.pushButton_exp_pdf_sheet.setText(_translate("DialogSchedaLapidei", "Exp schede Pdf ", None))
        self.pushButton_image.setText(_translate("DialogSchedaLapidei", "Charge image", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("DialogSchedaLapidei", "Tools", None))
