-- Crea gli utenti PostgreSQL corrispondenti agli utenti PyArchInit
-- NOTA: Cambia le password per sicurezza in produzione!

-- Crea l'utente admin
CREATE USER admin WITH PASSWORD 'admin123';
GRANT ALL PRIVILEGES ON DATABASE festo28_restored TO admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO admin;

-- Crea l'utente editor1
CREATE USER editor1 WITH PASSWORD 'editor1';
GRANT CONNECT ON DATABASE festo28_restored TO editor1;
GRANT USAGE ON SCHEMA public TO editor1;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO editor1;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO editor1;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO editor1;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO editor1;

-- Crea l'utente st1 (studente)
CREATE USER st1 WITH PASSWORD 'st1';
GRANT CONNECT ON DATABASE festo28_restored TO st1;
GRANT USAGE ON SCHEMA public TO st1;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA public TO st1;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO st1;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT ON TABLES TO st1;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO st1;

-- Crea l'utente guest
CREATE USER guest WITH PASSWORD 'guest';
GRANT CONNECT ON DATABASE festo28_restored TO guest;
GRANT USAGE ON SCHEMA public TO guest;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO guest;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO guest;

-- Assicurati che tutti gli utenti possano usare le estensioni
GRANT USAGE ON SCHEMA public TO admin, editor1, st1, guest;

-- Permessi specifici per le funzioni di concorrenza
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO admin, editor1, st1;

-- Mostra gli utenti creati
\du